### ISSUE TITLE
Linux support for the HelloVR sample

### ISSUE THREAD

**Issue by ChristophHaag** [ValveSoftware/openvr#10]
hellovr and pathtools use some windows-only stuff. There seems to be some stuff for linux support, but it's incomplete.

As you can see here: https://github.com/ChristophHaag/openvr/commits/master it wouldn't be much work to actually make it run on linux, but it would be preferable to actually use the cross platform compatible functions directly and to have a proper build system like CMake.

edit: Wrote some hacky cmake stuff. Only works on linux, but at least it should work. Build instructions at the end of the README.

**Comment by thegreatpissant** [comment]
I have compiled this my selft and used the repo mentioned above but neither seem to run.  I am always presented with a "VR_Init Failed" Message dialog and "Unable to init VR runtime: Hmd Not Found (108)"

This is with the nvidia drivers using the Oculus DK2 running the hello_vr sample with the -nocompositor flag.  Am running ovrd from sdk 0.5.0.1

The .local/share/Steam/logs for my app come back saying 
Thu Jun 11 01:44:00 2015 UTC - Unable to load driver oculus from /home/thegreatpissant/.local/share/Steam/SteamApps/common/SteamVR/drivers/oculus/bin/linux64/driver_oculus.so.
Thu Jun 11 01:44:00 2015 UTC - Unable to load driver null from /home/thegreatpissant/.local/share/Steam/SteamApps/common/SteamVR/drivers/null/bin/linux64/driver_null.so.
Thu Jun 11 01:44:00 2015 UTC - Returning HmdNotFound because the client-side presence check failed.

I can use Steam in VR mode but not run this openvr sample app.

I am not too clear on what exactly needs to be running steam side for this to work.

**Comment by ChristophHaag** [comment]
Hm, that sounds like the culprit:
`Unable to load driver oculus from /home/thegreatpissant/.local/share/Steam/SteamApps/common/SteamVR/drivers/oculus/bin/linux64/driver_oculus.so`

I think the SteamApps/common/SteamVR/ is the problem. I think it should be SteamApps/common/OpenVR/. Maybe update steamvr tools to beta and the steam client to beta and try again?

**Comment by thegreatpissant** [comment]
I have the beta steam client and beta SteamVR enabled.

Maybe it is the services I may not be running.  Is it just the ovrd and then run the app or do you have to also have steam running?

**Comment by ChristophHaag** [comment]
As far as I know, steam must be running AND steam must even be in vr mode.

Do you have the file /home/thegreatpissant/.local/share/Steam/SteamApps/common/OpenVR/drivers/oculus/bin/linux64/driver_oculus.so?
If yes, then maybe you can get away with

    ln -s /home/thegreatpissant/.local/share/Steam/SteamApps/common/OpenVR/ /home/thegreatpissant/.local/share/Steam/SteamApps/common/SteamVR/

Or maybe not, I don't know.

By the way: Yesterday night I updated my little fork after Valve pushed the OpenVR 0.9.2 update, but I haven't tested whether it still works.

**Comment by csherratt** [comment]
@ChristophHaag run `ldd /home/thegreatpissant/.local/share/Steam/SteamApps/common/SteamVR/drivers/oculus/bin/linux64/driver_oculus.so` and make sure you have all the libraries. If you are running a recent distro you may be missing `libudev0`.

**Comment by thegreatpissant** [comment]
That was the problem.  
>> ldd /home/thegreatpissant/.local/share/Steam/SteamApps/common/SteamVR/drivers/oculus/bin/linux64/driver_oculus.so

libudev.so.0 => not found

On fedora 21 created a symbolic link from /usr/lib64/libudev.so.1 to /usr/lib64/libudev.so.0

Started "ovrd" and the example app with the flag '-nocompositor'.

Thanks!!

**Comment by shazow** [comment]
Has anyone been able to get a recent version working on Linux?

I have ovrd building and running from [a forked 0.5.0.1 build](https://github.com/jherico/OculusSDK/). No missing linked libraries reported by ldd. Still getting the Steam-grey "Unable to init VR runtime: Hmd Not Found (108)" error window when I run the hellovr sample with -nocompositor. Steam logs show:

```
Sun Feb 28 2016 12:27:21.480633 - //=====================================================================================================================
Sun Feb 28 2016 12:27:21.480784 - vrclient startup with PID=1367, config=/storage/shazow/Steam/config
Sun Feb 28 2016 12:27:21.481018 - Unable to load driver lighthouse from /storage/shazow/Steam/SteamApps/common/SteamVR/drivers/lighthouse/bin/linux64/driver_lighthouse.so.
Sun Feb 28 2016 12:27:21.482163 - Could not create interface in driver oculus from /storage/shazow/Steam/SteamApps/common/SteamVR/drivers/oculus/bin/linux64/driver_oculus.so.
Sun Feb 28 2016 12:27:21.482443 - Returning HmdNotFound because the client-side presence check failed.
```

I'm using @ChristophHaag's forked repo to make it build on linux properly.

**Comment by thendrix** [comment]
I was getting a crash inside the vrserver inside CVRServer::Run() last I tried it, but there have been few updates since.  I'm using a DK2 as well with 0.5 SDK and leap motion works as well as it ever has.

Running with strace or a debugger can help narrow down the issue.  For example just look at the file operations to see if a runtime linked SO is missing:
$ strace -e trace=file ./hellovr -nocompositor

**Comment by ChristophHaag** [comment]
Haha this was still open.
