### ISSUE TITLE
Accessing the scene texture from driver

### ISSUE THREAD

**Issue by Mcsiv** [ValveSoftware/openvr#104]
Is there any way to access the scene texture from the driver? It would be great if it were possible to run a custom pixel shader code before it was passed to the compositor

**Comment by JoeLudwig** [comment]
This isn't currently supported.

What sort of thing do you want to do in that pixel shader? Maybe what you want is already supported...

**Comment by Mcsiv** [comment]
Thanks for your response! Yepp, you are correct and im saying something stupid in this case. I want to run a pixel shader after the compositor (not before) to pack some extra information into the stream (32bpp hdmi stream with 24bpp screens and use the remaining 8 bit to something else). It's looks like a "dirty hack", but better than try to synchronise the hdmi stream with an usb stream and do all that in the hardware side :) and it may have a few other possibility

**Comment by JoeLudwig** [comment]
Ok, no. That's not supported. :)

You should be able to prototype this by writing the bits you want to your render target, including lens distortion, and then submit your texture with Submit_LensDistortionAlreadyApplied. It's not clear that you'll be able to get HDMI itself to handle 32bpp, though. You might need to encode your extra data in some of the unused pixels in the corner instead of per pixel.

Once you get things running and are satisfied that it's the right approach we should talk about details. Obviously we could add something like this to the driver API, but we'd need a compelling reason to do it.
