### ISSUE TITLE
AddApplicationManifest() doesn't load manifest until SteamVR reboot

### ISSUE THREAD

**Issue by LibreVR** [ValveSoftware/openvr#106]
It looks like `AddApplicationManifest()` doesn't actually load the manifest until the next time the list of installed applications is rebuilt. From my experiments it looks like this list is only rebuilt when SteamVR is rebooted.

`AddApplicationManifest()` also has a parameter to specify a temporary manifest. However given that the list is only rebuilt when SteamVR is rebooted, this makes temporary manifests useless since they are forgotten after the reboot.

Can anyone explain and document the intended behavior? When are new manifests loaded and how should a newly installed application add its manifests?

**Comment by LibreVR** [comment]
I've come to the realization that SteamVR and OpenVR hold separate lists of installed applications. SteamVR only updates its list when SteamVR is rebooted and so will only show permanent manifests which are present when SteamVR starts up.

OpenVR on the other hand will actually add new applications to its list when `AddApplicationManifest()` is called.

**Comment by LibreVR** [comment]
Let me explain a bit about my usecase: For my application I need to add new application manifests to OpenVR dynamically based on which applications are currently installed. I'd also like these applications to show up in SteamVR itself for convenience.

Based on what I've seen there are three ways to do this:

1. Add a completely new permanent manifest for each installed application.
2. Add new entries to an existing permanent manifest. Then continue to remove and re-add the existing manifest to force a refresh.
3. Use a template manifest and adjust the arguments before launching the application. This doesn't allow for SteamVR integration.

It seems SteamVR itself uses option 2 to add its applications to OpenVR. It only has one manifests which is updated every time SteamVR is started.

**Comment by JoeLudwig** [comment]
Either 1 or 2 are fine. It's up to you how granular you want your manifests to me. If you do #2 you should definitely use your own manifest and not try to reuse Steam's as Steam will overwrite you randomly. Steam also updates the manifest file whenever an app that uses SteamVR is installed/uninstalled in the Steam library.

Whenever you update a manifest file just call AddApplicationManifest again to make sure it gets reloaded. SteamVR doesn't monitor the file for changes or poll so that's the best way to get it to update on a running system.

**Comment by LibreVR** [comment]
@JoeLudwig I never intended to use the SteamVR manifest. I was just comparing to how SteamVR was behaving.

I'll try calling `AddApplicationManifest` again, but from what I could see only OpenVR is affected by that call. The changes in SteamVR are only visible after a reboot of SteamVR.

However, since I seem to have some more odd behavior (see #105), I'll try fixing those issues first and then test it again.

**Comment by LibreVR** [comment]
@JoeLudwig Just tested it again, calling `AddApplicationManifest` doesn't seem to affect SteamVR until the next reboot. It does affect the OpenVR application list though, so I can still start the applications through my own interface.

**Comment by willswannackpluto** [comment]
@LibreVR Why did you close this? Did you find a work around? 

I can't seem to get it to work either. I'm running the latest OpenVR dlls and calling AddApplicationManifest. After that, I call LaunchDashboardOverlay with the correct application key and get "UnknownApplication". After restarting SteamVR and running the first application again, calling LaunchDashboardOverlay successfully runs the application.

Our goal is call SetApplicationAutoLaunch to true after the first launch (so our overlay will always be available when SteamVR is available). Due to the SteamVR reset requirement, this flag can only be set after adding the manifest, closing and reopening SteamVR, and then calling SetApplicationAutoLaunch.

We're using LaunchInternalProcess now for when the manifest hasn't been loaded yet, but it still awkwardly delays our ability to set AutoLaunch.

**Comment by JoeLudwig** [comment]
@ghost When you say it "doesn't affect SteamVR" do you mean that the application list in the Steam UI in the dashboard doesn't update with the new apps? Or some other piece of UI?

**Comment by kisak-valve** [comment]
Friendly reminder that @ghost is a catch all for accounts that do not exist anymore.

**Comment by JoeLudwig** [comment]
Shows what I know. :)

Anybody else then... Anyone know what the late Mr. Ghost might have meant?

**Comment by willswannackpluto** [comment]
@JoeLudwig I'm not sure what ghost meant regarding it updating OpenVR but not SteamVR.

My experience is if I add the application manifest and then immediately check to see if one of the provided applications is installed (or try to launch it or SetApplicationAutoLaunch), I get an UnknownApplication error in response.

If I turn off the application that added the manifest and restart it, I continue to get an UnknownApplication error.

However, if I turn off the application that added the manifest, then close and reopen SteamVR, then reopen the application that adds / launches from the manifest, it works. So it appears the "AddApplicationManifest" call is working but doesn't get recognized until SteamVR has closed and relaunched.

My ideal scenario is to add the application manifest and use SetApplicationAutoLaunch immediately. This way our dashboard application could start up immediately with SteamVR the next time it's launched and could be easily disabled in the settings menu. 

In our current process, to get this to work you need to add the application manifest, then close SteamVR and reopen it, and then you can call SetApplicationAutoLaunch, and then the next time SteamVR launches our application will as well.
