### ISSUE TITLE
Feature requests: Lite drivers, work without steam, ask wants to run VR mode or not

### ISSUE THREAD

**Issue by r57zone** [ValveSoftware/openvr#1090]
1. Lite driver contains a config with the display parameters (mode: direct or extended, if directed display id and rotation angle) and settings (lens distortion, ), as well as a dll to get the rotation, position and controllers data. This is suitable for most VR devices and will allow manufacturers to practically not update their drivers after updating the new SDK.
Examples folders:
```
driverslite
-driver
--driver.vrdrivermanifest
--win32
---driver.dll
--win64
---driver.dll
```
Example config:
```
{
	"enable": true,
	"displaymode": "direct",
	//"displaymode": "extended",
	//Offsets X, Y for extended mode
	"directModeEdidPid" : 43521,
	"directModeEdidVid" : 53794,
	"displayFrequency" : 60,
	"settings" : {
		"DistortionK1" : 0.91,
		"DistortionK2" : 0.93,
		"renderWidth" : 1920,
		"renderHeight" : 1080
	}
}
```
Drivers can be automatically added up from the "driverslite" directory by scanning the folder.

2. SteamVR has become popular and it would be cool to set it apart as an independent project. Not everyone uses Steam, give the opportunity to use SteamVR for any projects, any games of any stores. To do this select it in a separate project with a separate installer, this can be done on the site steamvr.com.

3. It would be nice to ask the user about whether he wants to run VR mode or not. In some games, the game starts in 2 modes at once, i have to close SteamVR, this is inconvenient.

**Comment by TheDeveloperGuy** [comment]
1) "A dll to get the rotation, position and controllers data" is basically what a SteamVR driver is right now. Direct mode can only be enabled for hardware that has been whitelisted by GPU vendors, there's nothing that Valve can do to make a particular headset work in "direct" mode. They could add some function to do lens distortion internally use Kn factors, but apart from that everything is already there. 

2) SteamVR can be used without Steam. Look at Viveport.

3) Is up to the game.

**Comment by r57zone** [comment]
@TheDeveloperGuy 
1. The point is to make simpler drivers that give only rotation data, position and button data of controllers. This is necessary so that the driver does not need to be updated.

**Comment by TheDeveloperGuy** [comment]
Valve maintains backwards compatibility with drivers developed with older OpenVR SDKs. I'm not aware of a single driver interface (they are versioned to avoid new features breaking older interfaces) that is no longer supported.

**Comment by r57zone** [comment]
How long will it be? 3 years? It will not last forever. Therefore they can ease the drivers and take only what need.

**Comment by TheDeveloperGuy** [comment]
@r57zone 

1. There is no (properly developed) driver that *needs* to be updated. It's possible to run drivers built 2 years ago on current SteamVR. If the driver doesn't work any more, it's a bug in the driver not lack of backward compatibility in SteamVR.

**Comment by r57zone** [comment]
Old compatibility will be removed sooner or later. Old compatibility may not work with new features.

**Comment by TheDeveloperGuy** [comment]
@r57zone

Look at the 'sample' driver supplied with the OpenVR SDK. Apart from the lens distortion it's just a container for reading those configuration values you gave as example and passing them to SteamVR. All that needs to be added to it is sensor reading for a particular headset.

**Comment by TheDeveloperGuy** [comment]
@r57zone

You're making up stories with "Old compatibility will be removed sooner or later". In the history of SteamVR this hasn't happened once. In any case, old software is not going to support new features (which are largely based around input methods at this point) so the driver is going to have to be updated in any case.

**Comment by TheDeveloperGuy** [comment]
There's nothing stopping anyone from developing a modular driver like this (it would probably only take a few hours). The problem is that only new drivers may choose to use that architecture (can't force it on everyone), which wouldn't solve the problem of old drivers not being updated.

**Comment by TheDeveloperGuy** [comment]
@r57zone

It's also possible to write a 'hook' driver for SteamVR, that will allow you to override the sensor and controller functionality for an existing driver that is no longer being updated or is closed source.

**Comment by JoeLudwig** [comment]
We intend to provide backward compatibility for drivers indefinitely, just like we do for apps. The Windows MR bridge driver is provided by Microsoft and uses the same driver interface as our internal drivers. We definitely don't want to leave those users behind.

We do **not** provide backward compatibility for "hook" drivers, and think it's a bad idea to depend on that approach for anything that is going to ship to end users. Hook drivers break, usually by crashing, because they defeat the interface compatibility in vrserver. They are the main reason people end up in safe mode. And there are some possible architectural changes on the horizon that would break them completely. Hooking vrserver in this way is not supported, and never will be.

I suggest you take a look at the driver sample. It is pretty much exactly what you're asking for:
1) You can read the config files you suggest and then call the APIs. It's backward compatible back to 0.9.20: https://github.com/ValveSoftware/openvr/releases/tag/v0.9.20
2)  Call "vrpathreg adddriver <path>" and your driver will be registered as an external driver in the same way that drivers from Steam are registered. That command is exactly what Steam does.
3) Non-VR-mode apps probably don't want SteamVR running at all. This is best accomplished by them never calling VR_Init in the first place, which means a driver can't participate in that decision. Steam apps can do that by configuring separate launch options for the two modes. Non-Steam apps are free to sort that out on their own.

**Comment by TheDeveloperGuy** [comment]
@JoeLudwig Agreed that "hook" drivers are a last resort, and will need to be recreated for every SteamVR release. It's a necessary choice in some (very limited) instances. 

Looking at @r57zone's project(s). It looks like he's trying to achieve what would normally require a "hook" driver, adding HMD tracking override to an HMD driver that has no source code available. It would be very useful if there was some other way to do that in SteamVR (hint hint).
