### ISSUE TITLE
Debug commands removed

### ISSUE THREAD

**Issue by Jonas-Mikkelsen** [ValveSoftware/openvr#1167]
In the debug commands added there were some setting to enable to user to disable mura correction.

I was wondering why this command was removed without any message or information whether it would be returning.

**Comment by jeremyselan** [comment]
That had been accidentally exposed in the prior release -- we weren't expecting users to want to be able to toggle it.  Can you share more about your use case for toggling it?

**Comment by Jonas-Mikkelsen** [comment]
Many users like me had their HMD's shipped with quite aggressive mura correction, which was visible in even bright scenes. In my case, the mura correction is so aggressive that it is distracting and some cases disorientating.

I would love to see this debug command return or just figure out how to toggle it manually if that is possible.

**Comment by haywirephoenix** [comment]
A lot of people are upset aboutthe settings disappearing. Please re-enable black_clamp_toggle and mura_correction_toggle (or tell us how to) I'm begging you! I don't mind black smear I just want true black levels when in dark scenes instead of grey noise. It's important for immersion in games with dark scenes or space sims.

Just bought a vive pro with black_clamp_toggle and mura_correction_toggle in mind. I had them bound to "B" and "M".

Rolled back to the earlier build that has it but input doesn't play well with games. 

Interestingly it still exists in debugcommands.js I hoped it wasn't and simpy re-adding them would work.

Also tried adjusting black_clamp using lighthouse_console.exe in the config. 

If you guys re-exposed these settings and even added a black clamp level slider to the advanced settings you would be gods!

**Comment by haywirephoenix** [comment]
Incase anyone wants the last steamvr build with black_clamp and mura_correction_toggle and doens't want to download all the depots from the developer console, here's a link to everything packed for you

https://drive.google.com/open?id=1-O58ETo7a0Rbf9aYHpYUQMrSaskUweiY

**Comment by haywirephoenix** [comment]
Complete silence from the devs on this subject. Maybe they were told to remove it to level the playing field with the Index. Is that legal?
