### ISSUE TITLE
ShowMirrorWindow() doesn't work

### ISSUE THREAD

**Issue by sergioberg** [ValveSoftware/openvr#1173]
SteamVR 1.7.3:
ShowMirrorWindow() and HideMirrorWindow() do not work
SteamVR 1.6.10:
both work as expected

**Comment by aleiby** [comment]
Thanks.  These functions have been deprecated with the new VR View and will be removed from the API in a future update.  Did you have a specific need for this functionality, or were just reporting?

**Comment by sergioberg** [comment]
> Thanks. These functions have been deprecated with the new VR View and will be removed from the API in a future update. Did you have a specific need for this functionality, or were just reporting?

@aleiby It is used in fpsVR (https://store.steampowered.com/app/908520/fpsVR/ - i'm developer), used as desktop's util, for example for opening mirror and pressing Shift + A (via keystroke emulation) without interaction with keyboard.

**Comment by aleiby** [comment]
I've gone ahead and exposed all the debug commands via a vrmonitor url handler, so you can now use vrmonitor://debugcommands to pop up the window and then perform your keystroke emulation or execute the command directly via vrmonitor://debugcommands/some_command (which will be more reliable since users can now override the default keybindings).  This is in the current beta now (v1.7.5).

**Comment by sergioberg** [comment]
> I've gone ahead and exposed all the debug commands via a vrmonitor url handler, so you can now use vrmonitor://debugcommands to pop up the window and then perform your keystroke emulation or execute the command directly via vrmonitor://debugcommands/some_command (which will be more reliable since users can now override the default keybindings). This is in the current beta now (v1.7.5).

@aleiby wow! thanks!
