### ISSUE TITLE
GetOverlayTransformAbsolute broken in SteamVR beta 1.9.7

### ISSUE THREAD

**Issue by bddckr** [ValveSoftware/openvr#1264]
Posting here to get some eyes on this post, over in the Steam SteamVR Developer forums:
https://steamcommunity.com/app/250820/discussions/3/1626286205691646757/#c1752394282892897400

Can we get some help again @JoeLudwig? 🤞

**Comment by JoeLudwig** [comment]
This function is no longer supported on dashboard tabs. They're positioned in a totally different way that doesn't write the transform.

**Comment by bddckr** [comment]
@JoeLudwig Let me clarify here:

For dashboard overlays `GetOverlayTransformAbsolute` was broken in 1.8.3, restored in 1.8.5 and from now on (1.9.7+) it will be gone forever? And that change is intended to be a breaking backward-incompatible change, forcing apps compiled against the old SDK to now crash, or update to remove the functionality completely?

Why the sudden change? Why not keep a getter-only API? Any chance we get a replacement to get the position the dashboard spawns the overlays at least?

**Comment by sergioberg** [comment]
@JoeLudwig Please, we need an alternative way to get the position of the dashboard tab.

**Comment by JoeLudwig** [comment]
> And that change is intended to be a breaking backward-incompatible change, forcing apps compiled against the old SDK to now crash, or update to remove the functionality completely?
That's right. Underlying changes in the way dashboard tabs are positioned are the root of all this. Starting in the 1.9 SDK they are now their own transform type and have no getter.

Are you getting a crash when you try to retrieve the transform? It should just return an error.

**Comment by bddckr** [comment]
Yeah it returns an error. I believe the crash was due to me hitting a concurrency bug on my end.

I'm not compiling against any new SDK and thus this is breaking my app as it is.

Any chance we get a replacement to get the transform the dashboard overlays spawn at by default at least? Basically an API that would return the transform of the overlay at that moment in time when called (as the transform depends on the HMD transform at that time).

**Comment by elvissteinjr** [comment]
Doesn't everything have a calculable play space-relative/absolute transform, even if it's just in the very moment of the function call? 

I second the notion of wanting some kind of alternative at least. Calculating the dashboard position from scratch is not impossible, but also not properly documented. I think the code was posted in comment of an old issue here before, but there were some variables introduced since then such as HMD defined dashboard distance and who knows what else.

A function returning the absolute transform of where dashboard overlays are positioned (or similar, I know the actual position depends on overlay dimensions) would be very useful.
