### ISSUE TITLE
Predefining which base stations to use

### ISSUE THREAD

**Issue by piede828** [ValveSoftware/openvr#1397]
Assuming there are multiple base stations in an area an I want to interact just with some of them, is it possible to tell OpenVR to only consider certain base stations for the tracking (maybe by passing the ID)?

**Comment by JoeLudwig** [comment]
There's no mechanism for this in the API. The best you can do is turn off the base stations you don't want to use.

Base stations handle any number of receiving objects, though, so generally what people do in large rooms is tile the coverage of 2.0 bases so that every spot in the room is covered by 3-4 bases. Base stations end up getting selected automatically based on which stations the headsets and controllers can see.

**Comment by piede828** [comment]
Would it be possible to ignore some of them then? It’s a shame if you have multiple universes of bases but you can cycle through them as you might need
