### ISSUE TITLE
VRCompositor_ReprojectionReason_Cpu and VRCompositor_ReprojectionReason_Gpu always 0

### ISSUE THREAD

**Issue by sergioberg** [ValveSoftware/openvr#1462]
SteamVR beta 1.15.4
Headset: Index
Reprojection flags VRCompositor_ReprojectionReason_Cpu and VRCompositor_ReprojectionReason_Gpu flags are always 0
In my opinion, these flags never worked, in any version of SteamVR and API.

**Comment by aleiby** [comment]
These were added before async reprojection was implemented.  They were used by the older "interleaved reprojection" system.
In async mode, VRCompositor_ReprojectionReason_Cpu still gets used if apps call ForceInterleavedReprojectionOn, which while not using the old interleaved reprojection system, still has the effect of telling the compositor to throttle the application at half rate.  If you look at the mini perf graph on the SteamVR desktop widget (disabled by default), you will see a little blue tick at the bottom of frames while this is set.  This is used by Half-Life: Alyx when it detects that it cannot make framerate due to cpu bottleneck.

**Comment by sergioberg** [comment]
thanks for the explanation
