### ISSUE TITLE
What happened to OpenVR SDK 1.15?

### ISSUE THREAD

**Issue by TheDeveloperGuy** [ValveSoftware/openvr#1498]
In a break from tradition, SteamVR 1.15 has been out for some time now without a corresponding updated SDK. Is a new SDK imminent, or is it being skipped for this SteamVR release?

**Comment by JoeLudwig** [comment]
I just looked at the diffs what would be in a 1.15 SDK and there are essentially no changes. So there's no need to ship an SDK.

The rate of change in the OpenVR interface is slowing significantly as we move toward OpenXR. We will have a 1.16 SDK for sure (because I know of at least one change in there) but it's hard to say how many more there will be.
