### ISSUE TITLE
Half Life Alyx Ignores Movement Controller bindings

### ISSUE THREAD

**Issue by pottedmeat7** [ValveSoftware/openvr#1553]
Input from `/user/treadmill` by itself does not work in Half Life Alyx, it always requires the player to push the Thumb stick. 
I'm not sure if this is an issue with OpenVR or the game... Shouldn't I be able to remove the Thumb stick binding from the controller completely, and have input come from the 3rd `/user/treadmill` controller bounded to the "Walk" action in Half Life Alyx?

**Comment by Rectus** [comment]
This is likely due to how the game handles controller roles. Alyx uses the IVRInput::Get/SetDominantHand() functions to swap between left and right handed mode on the fly, so it will have to filter the action inputs to not get input from the wrong hand. It probably does that by checking if the action was triggered by the dominant hand, so any other devices would get filtered out too.

Depending on how pedantic it is with checking the input, you could try cheating the system by binding the walk input to the non-dominant hand.

**Comment by pottedmeat7** [comment]
I tried binding to both left (non-dominant) and right (dominant). Still doesn't accept the `/user/treadmill` input as the trigger for the `Walk` action. 
I do believe this has something to do with how the game is accessing, filtering, input, because I remove the `Walk` action entirely from my physical controller bindings, and only bind `Walk` to my `/user/treadmill` virtual device. 
The game reacts to this input, but only when I push the Thumb stick on my non-dominant controller. 
The binding for Thumb stick by itself doesn't apply the `Walk` action either, so the game doesn't really care where the `Walk` action comes from but it requires that action and the non-dominant Thumb stick to be held to work... 
Don't know if this is fixable from OpenVR's side, but it's functionality not to specification as what the bindings is really supposed to do...

**Comment by Rectus** [comment]
Looks like it uses the `/actions/move/in/TeleportTurn` action for the continuous movement axes, walk is just the toggle for clicking the stick. It's weird that they didn't make a separate action with a clear name for the movement.

**Comment by pottedmeat7** [comment]
Oh that works! I thought I had tried those actions before but must have missed that combination!
I guess since it is possible just very unclear I will close this ticket. Thank-you for the help!
