### ISSUE TITLE
How to use IVRServerDriverHost::RequestRestart

### ISSUE THREAD

**Issue by danwillm** [ValveSoftware/openvr#1702]
I'm trying to work out how to ask SteamVR to restart itself from the driver interface.

I've seen that there is a method within IVRServerDriverHost which seems to provide the desired functionality, but I'm not sure what I should be specifying for `pchExecutableToStart` - is this an extra executable that I can run before? (after?) SteamVR has restarted, or does this need to be the path to the SteamVR executable?

I've tried calling this method with: the message I wish to show for the first parameter and the rest as empty arguments, specifying a custom exectuable and its path, and `vrstartup.exe` and its path, but nothing seems to happen when doing so.

Is this method known to be broken? or is there something that I'm missing?

Thanks in advance.

**Comment by TheDeveloperGuy** [comment]
It's been a while now, so details are a bit fuzzy... IIRC this feature was added on my request (as I need to do a SteamVR restart from my driver). However, they developed it without consulting me at all, and so when the time came to use it, I found it wasn't usable for my purpose. So, I went ahead and developed my own version. It's a complicated mess (which is why they added this in the first place). AFAIK, it's never been used by anyone, and so it is quite likely that it was broken in subsequent SteamVR updates. In part (IIRC), it relies on the dashboard notification system, which itself is definitely broken. So, maybe it will work if they ever fix that (unlikely, as once again it is a feature that hardly anyone uses). As a general rule, if an OpenVR feature doesn't work, or doesn't work to your liking, you need to develop your own. This will save you a lot of time and frustration in the long run, as bugs don't generally even get acknowledged, let alone fixed, and the OpenVR devs are a lot less active now than they were when I was developing my driver. 


The way to do this yourself is to request SteamVR to quit (via driver event), and spawn a process which will wait for SteamVR to quit, kill it if it doesn't in a timeous matter (did I mention SteamVR is buggy), and then start it again. If Valve devs actually responded to bug reports or listened to developers, this wouldn't be necessary. However, that is not the world we live in.

**Comment by TheDeveloperGuy** [comment]
Use this to request SteamVR to quit:

	// Shut down SteamVR
	VREvent_Reserved_t data = { 0, 0 };
	vr::VRServerDriverHost()->VendorSpecificEvent(m_unObjectId, vr::VREvent_DriverRequestedQuit, (VREvent_Data_t&)data, 0);

**Comment by danwillm** [comment]
Thanks for this. What I'm looking for is really a way to show a message to the user and request steamvr be restarted (essentially a firmware incompatibly message to prompt the user to update it and restart). This option seemed to be the most valuable way to do so, but there was also` IVROverlay::ShowMessageOverlay`

**Comment by danwillm** [comment]
I think I'll end up using your suggestion of sending a quit event and some sort of process that just displays a particular error message. Thanks for your input!
