### ISSUE TITLE
Question: Is there a way to log to the steam vr log files from an app?

### ISSUE THREAD

**Issue by alex-freeaim** [ValveSoftware/openvr#1759]
In a driver, I can log to Steam's log files (specifically vrserver.txt) via this code:

```
vr::VRDriverLog()->Log("my log");
```

The `vr::VRDriverLog` is available in `openvr_driver.h`.

I don't see a similar option to log in `openvr.h`, which an overlay or utility app would use. Is there a way to log to Steam's log files using functionality in `openvr.h`, similar to how the log function works in `openvr_driver.h`?

Thanks!

**Comment by TheDeveloperGuy** [comment]
vrserver.txt log file is for the server and things (ie. drivers) loaded by it. Applications shouldn't be logging anything in there. If your application is part of your driver, you can use IPC mechanisms to pass the messages back to your driver so that it can log them. Otherwise your application logging should be done in its own log file.

**Comment by alex-freeaim** [comment]
Okay, thanks for the explanation!
