### ISSUE TITLE
SteamVR_ControllerManager Refresh

### ISSUE THREAD

**Issue by bostelk** [ValveSoftware/openvr#196]
In `Refresh()`

The left and right controllers are connected, but both `GetTrackedDeviceIndexForControllerRole(ETrackedControllerRole.LeftHand)` and `GetTrackedDeviceIndexForControllerRole(ETrackedControllerRole.RightHand)` are returning  `OpenVR.k_unTrackedDeviceIndexInvalid`.

This leaves only the right controller active. The left controller should also be active as it has a valid and connected device id (4).

How does SteamVR set _LeftHand_ and _RightHand_?

**Comment by JeffLeinbaugh** [comment]
This was fixed in SteamVR beta 1468372130 on 7/12. If a game starts before Left and Right controllers have been set, a temporary assignment is made, so GetTrackedDeviceIndexForControllerRole() will return a valid index (as long as controllers are connected). Once the assignment is locked in, OnTrackedDeviceRoleChanged will be called to update the results.
