### ISSUE TITLE
Incorrect resolution/mode selection in direct mode

### ISSUE THREAD

**Issue by godbyk** [ValveSoftware/openvr#336]
How does SteamVR determine which resolution to use in direct mode?

I have an HMD that can operate in both 1920×1080 and 1080×1920 modes. The portrait (1080×1920) mode is preferred as it's the faster rendering path. (In the landscape mode, an internal FPGA needs to cache the incoming frame before it can rotate it and pass it on to the display.)

When SteamVR goes into direct mode, it's putting the HMD into the landscape resolution even though the original extended-mode resolution was portrait.

A few questions:

1. Is there a way to instruct SteamVR to choose a particular resolution?
2. If not, is there a way to determine which resolution SteamVR put the display in?
3. If not, how do I know what to specify for the window bounds, texture size, eye viewports, rotations within the distortion correction function, etc.?
4. What is SteamVR's algorithm for determining which resolution to use in direct mode? Will it consistently choose the same resolution?

**Comment by godbyk** [comment]
@JoeLudwig @jeremyselan Do you have any insight on this?

**Comment by aleiby** [comment]
Joe actually just checked in a change today which should fix this on nvidia hardware.  Currently, it just uses the first largest mode it finds assuming that is the native resolution.  With his change, it'll use the values the driver specifies for windows bounds.  For amd, we just use the default mode (which hopefully is correct since you have to setup direct mode with their driver).
