### ISSUE TITLE
Building on Windows 10 x64

### ISSUE THREAD

**Issue by aprentis** [ValveSoftware/openvr#363]
I`m trying to build OpenVR on Windows. While doing readme instructions i couldn`t get where to place SDL2 Library. So then cmake said "unsupported compiler".  Where could i find a step-by-step instruction for Windows x64?

**Comment by tcoppex** [comment]
Hi @aprentis,
the SLD2 runtime binary was not provided on the repository for Windows x64 (unlike the x32 version).
You will need to download it from the official site @ [www.libsdl.org/download-2.0.php](www.libsdl.org/download-2.0.php) and copy it in
_openvr/samples/bin/win64/_ alongside the others binaries.

Cheers

**Comment by aprentis** [comment]
I`ve copied SDL2, but it still goes just like this. 
Any ideas? 

![2017-01-17_18-08-47](https://cloud.githubusercontent.com/assets/17255184/22025851/17771eda-dce0-11e6-98cd-1f95fe3ab584.png)

**Comment by tcoppex** [comment]
Okay thanks @aprentis, 
as you have stated in you first message it is a problem with the _unsuported compiler_ fatal error.

The culprit is a new and dreadful policy starting from CMake 3.1 which interprets differently variables in if-elseif cases. To fix this, just add the line `cmake_policy(SET CMP0054 OLD)` after `cmake_minimum_required(VERSION 3.0.2)`.

There is however an even more elegant fix which consists to change every `if(${VARIABLES} MATCHES "Wonderful string")` tests condition with `if("${VARIABLES}" STREQUAL "Wonderful string")`.

My bad really, I may have changed the minimum CMake version required without testing on both platform before the pull request..

Thanks for the head-up 👍

**Comment by aprentis** [comment]
Thanks @tcoppex ,

Unfortunately, cmake_policy(SET CMP0054 OLD) does not make any changes. Still "unsupported compiler". 

The "elegant" fix works OK!

**Comment by tcoppex** [comment]
Great :wink:

**Comment by aprentis** [comment]
However, there were more mistakes during the last step. 

I used it just like it was written: 

`To build, simply type:

cmake --build . --target all --config Release`

I`ve got an error with no such project.  

In build directory there are two projects ALL_BUILD and ZERO_CHECK, and openvr_samples.sln as well. 

I`ve tried "cmake --build . --target zero_check --config Release" and it was built OK. 

Then i`ve tried "cmake --build . --target all_build --config Release" and got many diiferent mistakes. 

In the end, i`ve tried to build the openvr_samples.sln with MSVS2015 and (wow!) got only 5 errors with same type(see screenshot). ![2017-01-18_12-35-03](https://cloud.githubusercontent.com/assets/17255184/22058644/b82ba8a6-dd7a-11e6-8f67-f2d0d04a98df.png)


I have a bad feeling about it, but maybe i`m really do something wrong with it?

**Comment by tcoppex** [comment]
Okay, it was due to invalid MSVC compiler flags, I really don't know how I haven't seen this before..
Check the PR for the fix.

Many thanks 😃

**Comment by aprentis** [comment]
Finally, it was built! Thank you!

**Comment by off99555** [comment]
When you install Qt, what components do you choose? What is the required component for OpenVR?
Because if I install everything it takes 42 GB!
![image](https://user-images.githubusercontent.com/15215732/56716975-cec6be80-6765-11e9-9008-1b2b44216ded.png)
