### ISSUE TITLE
Controller Events Issues

### ISSUE THREAD

**Issue by SilentKim** [ValveSoftware/openvr#377]
I use C++ and OpenGL to code my program instead of Unity. I want to listen and process controller event, but I can't find the interface of the events  like double click, button down event and button up event. My code to process controller events is like
`vr::VRControllerState_t state;
		if(m_pHMD->GetControllerState(i, &state, sizeof(state)))
		{
			m_rbShowTrackedDevice[ i ] = state.ulButtonPressed == 0;
			if (state.ulButtonPressed & vr::ButtonMaskFromId(vr::k_EButton_ApplicationMenu))
			{
                            do something.
			}`
Do you know how to listen other events? Thank you.

**Comment by destrofer** [comment]
As far as I've seen there are no double click events in OpenVR. You could implement it in your application quite easily. I will write samples of code assuming you are running your code in a loop for every frame.

```CPP
int doubleClickTimeout = 0; // A static field somewhere or a variable in a global scope

vr::VRControllerState_t state;
int ticks = GetTickCount();
if(m_pHMD->GetControllerState(i, &state, sizeof(state))) {
    m_rbShowTrackedDevice[ i ] = state.ulButtonPressed == 0;
    if (state.ulButtonPressed & vr::ButtonMaskFromId(vr::k_EButton_ApplicationMenu)) {
        if( ticks < doubleClickTimeout ) {
            onDoubleClick();
            doubleClickTimeout = 0;
        }
        else {
            onClick();
            doubleClickTimeout = ticks + 500; // setting timeout to current time + 0.5 seconds
        }
    }
}
```

This will call `onClick()` and if you press within the time limit (0.5 sec) again it will call `onDoubleClick()`.

You might want to have onClick() to be called only if double click time has expired without a second click:
```CPP
int doubleClickTimeout = 0; // A static field somewhere or a variable in a global scope


vr::VRControllerState_t state;
int ticks = GetTickCount();
if(m_pHMD->GetControllerState(i, &state, sizeof(state))) {
    m_rbShowTrackedDevice[ i ] = state.ulButtonPressed == 0;
    if (state.ulButtonPressed & vr::ButtonMaskFromId(vr::k_EButton_ApplicationMenu)) {
        if( ticks < doubleClickTimeout ) {
            onDoubleClick();
            doubleClickTimeout = 0;
        }
        else {
            doubleClickTimeout = ticks + 200; // I reduced this to 0.2 seconds or click would have a very lagged feel to it
        }
    }
}

// This could be right after your controller state check
// or somewhere over the rainbow in a constantly running loop
// or maybe even right after rendering
if( doubleClickTimeout > 0 && GetTickCount() >= doubleClickTimeout ) {
    doubleClickTimeout = 0;
    onClick();
}
```

Of course you might want to use something different than GetTickCount(). Its all up to you :)

As for button up and button down: you could actually handle events VREvent_ButtonPress, VREvent_ButtonUnpress, VREvent_MouseButtonDown, VREvent_MouseButtonUp (see [IVRSystem::PollNextEvent()](https://github.com/ValveSoftware/openvr/wiki/IVRSystem::PollNextEvent)).

Otherwise:

```CPP
uint64_t previousButtonState = 0; // A static field somewhere or a variable in a global scope

vr::VRControllerState_t state;
if(m_pHMD->GetControllerState(i, &state, sizeof(state))) {
    m_rbShowTrackedDevice[ i ] = state.ulButtonPressed == 0;
    uint64_t mask = vr::ButtonMaskFromId(vr::k_EButton_ApplicationMenu);
    if ((state.ulButtonPressed & mask) && !(previousButtonState & mask) ) {
        onPress();
    }
    else if (!(state.ulButtonPressed & mask) && (previousButtonState & mask) ) {
        onRelease();
    }
    previousButtonState = state.ulButtonPressed;
}
else
    previousButtonState = 0;
```

**Comment by SilentKim** [comment]
Thank you for you help, that's useful for me.
