### ISSUE TITLE
Proper way to use OpenVR as git submodule?

### ISSUE THREAD

**Issue by nlichtenberg** [ValveSoftware/openvr#397]
What would be the proper way to add openvr as a git submodule in another project?

The CMakeLists make use of `CMAKE_SOURCE_DIR`.
Afaik, this failed the compilation when compiling my root project, which builds openvr as a submodule.

Changing occurences of `CMAKE_SOURCE_DIR` to `CMAKE_CURRENT_SOURCE_DIR` _(precisely in /openvr/CMakeLists.txt lines 42-44 and openvr/src/CMakeLists.txt line 25)_ enabled me to compile everything.

But how can I include openvr as a submodule  without changing its files?

**Comment by godbyk** [comment]
For [SteamVR-OSVR](https://github.com/osvr/SteamVR-OSVR), I have OpenVR as a submodule, but instead of using CMake's `add_subdirectory()`, I just added `openvr/headers` to the `target_include_directories()`. (I'm not building the OpenVR library from source, but rather relying on the system-installed copy provided with SteamVR.)

**Comment by nlichtenberg** [comment]
That works for me, thanks!
