### ISSUE TITLE
What is 'popover_lowbattery_hmd_header'?

### ISSUE THREAD

**Issue by TheDeveloperGuy** [ValveSoftware/openvr#408]
I've implemented all of the power and battery status aspects of my HMD driver, and have come across this message (and 2 other similar ones) when the HMD battery is running low and I hover the mouse over the HMD icon in SteamVR. 

I'm assuming that I should be providing something for this, but what is it? An icon? A message? Where do I provide this? Can't find any mention of this anywhere...

**Comment by JoeLudwig** [comment]
This is a string in our string table that's missing because we weren't thinking about HMDs with batteries.  It'll be fixed in an upcoming beta (probably in a few weeks.)

Same with the other strings as long as they are one of:
"Popover_LowBattery_HMD_Header" "HMD ready with low battery"
"Popover_LowBattery_HMD_Description" "This HMD is connected and tracking but the battery is low."
"Popover_LowBattery_HMD_Action" " "
"Popover_LowBattery_HMD_ActionURL" " "
