### ISSUE TITLE
Getting "DXGI thread failed to get SDL display index" after driver loads

### ISSUE THREAD

**Issue by codalyn** [ValveSoftware/openvr#422]
Hi!

I'm developing an OpenVR driver for a custom headset that's being developed by my client and I've run into a little snag: when I set Prop_EdidVendorID_Int32 and Prop_EdidProductID_Int32 to the pair that identifies the display used in the custom headset, I consistently get the following error after my driver is loaded:

- Loaded server driver my_hmd1 (IServerTrackedDeviceProvider_004) from [...]
- Active HMD set to my_hmd1.1
- Processing message VRMsg_Connect from vrmonitor (15012) took 0.0169 seconds
- **DXGI thread failed to get SDL display index**

Anyone familiar with this particular error? What can I do to prevent it from occurring?

Thanks,
Jim.

**Comment by TheDeveloperGuy** [comment]
This error means that OpenVR wasn't able to figure out which "monitor" output (in Windows) your HMD display is using. If it is using a simulated (VGA) or real display output (HDMI), it means that you've given OpenVR the wrong screen x,y pos and/or fullscreen resolution. If you're using the Oculus/Direct OpenVR interface and your HMD isn't backed by a 'real' monitor output you'll also get this message, but it doesn't matter (neither can you make it go away). 

So, it boils down to whether this is stopping you or not. If it isn't, ignore it, if it is, you need to specify your window co-ordinates and size better so that OpenVR/SDL can identify which 'monitor' is being used for the HMD.

**Comment by codalyn** [comment]
I'm not using the IVRDriverDirectModeComponent interface and my display is a real display output connected through HDMI.

The window co-ordinates I'm passing to the system are <0, 0> for position and <2160, 1200> for size. The latter matching the resolution of the display. My display isn't on the desktop, though. What co-ordinates _should_ I pass in for a display not connected to the desktop?

I wasn't sure this is what's blocking me, but it stuck out in the vrserver log. Something is causes the whole vr system to shutdown when loading my driver... just gotta find out which something that is. Maybe this is not it?

**Comment by TheDeveloperGuy** [comment]
That is a good question! I've only developed 'Extended' mode and Oculus/Direct drivers, so can't comment on that. I'd expect that OpenVR would figure out the display index from the EDID. Are you certain you're giving the correct values? Also, AFAIK, you need to whitelist your display EDID with the GPU's display driver.

**Comment by TheDeveloperGuy** [comment]
Also, I'd say that this is probably your "show stopper". It's not possible (AFAIK) for the compositor to create it's window (and hence be able to display anything on the HMD) with this error, in a non Oculus/Direct driver.

**Comment by codalyn** [comment]
Yeah, that's what I'm thinking now too.

Unfortunately, from what I can find on the web, it sounds like whitelisting the display EDID with the GPU driver is not an easy thing to do. Clearest info I could find is from `[OSVR](https://github.com/OSVR/OSVR-Docs/blob/master/Extending-OSVR/AddingHMD.md#supporting-direct-rendering)`, but what's suggested there sounds like complete overkill. I don't need (or want) AMD or nVidia to whitelist my display in their general release driver. The headset we're building is never going to be manufactured at scale, but rather will be a low-volume production run for use in a theme park ride of sorts and used only on machines we control... I'll guess I'll go have a chat with AMD / nVidia to find out if they can help me with this!

Thanks for the help so far, @TheDeveloperGuy! Much appreciated! :)

**Comment by TheDeveloperGuy** [comment]
In that case, I'm not sure I'd bother. If it's running in a controlled environment, what would be the value? Of course it's "better" to use "direct mode", but the value in that is minimizing user error/confusion. If it's not an end-user configurable system, you don't get any real advantage with "direct mode" (AFAIK).

**Comment by codalyn** [comment]
Isn't direct mode also supposed to give you better performance? Or is that all just marketing blah blah then?

That aside, the particular display used in this HMD doesn't reliably work as an extended display. My life would be a lot easier if that were the case...

**Comment by TheDeveloperGuy** [comment]
Not that I know of. I think maybe the "VR-Direct" marketing campaign (by nVidia) lumped in a bunch of other tech at the same time that does improve performance (eg. timewarp, VR-SLI etc.) so that may be where you're getting that from. Also Windows doesn't have to manage the background for a non-desktop display, so you save a bit of memory perhaps. If your HMD doesn't work reliably as an extended display (what does that mean?), I wouldn't expect it to work more reliably as a direct mode display. Unless you mean sometimes Windows changes the display co-ordinates and it's a PITA to update the SteamVR config files, in which case I'd suggest you put some monitor detecting logic in your driver and work out the values at run-time.

**Comment by russell-taylor** [comment]
DirectMode on nVidia and AMD reduce rendering latency by one frame as compared to rendering to an on-screen (Extended mode) window.  On Pascal-series hardware, nVidia drivers also support pre-emptive priority rendering, which OSVR (and presumably others) use to enable ATW to update the view even when the app takes longer than a frame rate to render.

**Comment by codalyn** [comment]
@TheDeveloperGuy : What we're seeing is that the display functions normally on some machines, while on others it is recognized (as in DXGI is aware of it), but Windows is not able to extend the desktop to it.  I'll be the first to admit that feels a little fishy... but then again, maybe not entirely unexpected considering it's not a consumer part. I've asked my client to poke the display vendor about this issue.

@russell-taylor Thanks for chiming in! Reducing rendering latency by one frame is definitely welcome.

**Comment by TheDeveloperGuy** [comment]
@codalyn Ugh, that's not promising. Seems like a signalling issue of some kind.

@russell-taylor I see this from you last year, anything changed?
 
"Currently, the solutions are vendor-specific. You'll need to contact nVidia to get them to add your device to their driver white-list. Be aware that they have stopped DirectMode support for non-HDCP-compliant HMDs on laptops and on systems with multi GPUs (and they are warning that we should support it on any display going forward).

AMD has a different approach to getting devices registered, so you should contact them as well.

On the plus side, there is an API upgrade working its way through Microsoft that should provide a vendor-independent solution. We're tracking it and plan to release a new driver when it comes out. At that point, the entire rendering chain should be open source, because it will be using public APIs and not vendors-specific ones. I don't have an ETA for this, other than it was supposed to have been out last August."

**Comment by russell-taylor** [comment]
Still waiting for the new API to appear, I'm afraid.  We've been keeping up with the new driver releases and getting HMDs added.  You could contact Yuval Boger at Sensics if you want help getting the display working in DirectMode.

**Comment by JustFeng** [comment]
@codalyn  
In ExtendedMode(Means use a second monitor and   SteamVR will run a  vrcompositor)
Just like TheDeveloperGuy said 
 DXGI thread failed to get SDL display index  Usually caused by   wrong screen x,y pos and/or fullscreen resolution

see  in windows  the conpositor x,y positon may not be 0,0 but be 1920,0
(means your main mornitor of your computer resolution width,height zero);
or just use GetSystemMetrics( SM_CXSCREEN );
---------------------------------------
in other cases
to figue out the xy pose is easy 
persume your the resolution of your Main Screen is <W,H>
the top left corner of  [1st]monitor  is <0,0>   then the top right is<W,0>
if [2nd] monitor is your HMD  your Position data should be <W,0>
(i don't know if you could understand  Just MOVE your HMD Screen(in windows settings) AND Figure Out The relative coordinate Form the top left corner of [1st]monitor   )
(just in case  some time your HMD will be the [1st]monitor...JustUSE <0,0>)
![image](https://cloud.githubusercontent.com/assets/10377945/23804874/ad8ce474-05f6-11e7-951b-1ca1ac7f9451.png)

 @TheDeveloperGuy  may i ask u about the whitelist EDID and if i can just change my HMD's EDID How should i do it (or just stimulate Oculus???) and....just impliment IVRDriectMode blah blah will then enable DirectMode??? Thx

**Comment by TheDeveloperGuy** [comment]
@JustFeng I don't know how you would go about whitelisting your HMD, you will need to contact nVidia & AMD for that. You would need to change the EDID in your HMD's hardware. IVRDirectDriverMode has nothing to do with direct mode (it just has a bad naming choice). I think it's safe to say that unless you are mass-producing a HMD, or using a HMD that is already white-listed you can forget about "direct mode".

**Comment by codalyn** [comment]
I finally got a little bit further with this issue. 

Turns out our original problem was caused by faulty EDID data, which has now finally been resolved by the display manufacturer. Subsequently, I'm no longer seeing the DXGI error in the vrserver log.

Unfortunately, the compositor refuses to work even with the new EDID. This is the debug spew I get in the vrcompositor log:

Tue Apr 11 2017 11:22:25.520 - Headset display is on desktop
Tue Apr 11 2017 11:22:25.523 - Invalid adapter (-1, -1) specified!
Tue Apr 11 2017 11:22:25.524 - Failed to initialize compositor
Tue Apr 11 2017 11:22:25.524 - Failed to start compositor: VRInitError_Compositor_Failed

I get the same error whether or not I enable direct mode in OpenVR and/or whether or not I provide the EDID info for direct mode to OpenVR from my driver.

With the display in extended mode, I query the appropriate monitor rect and pass that as the window x/y, width, height to the driver, which on my test machine means passing in <-2160,0> for position and <2160,1200> for size. Of course, I stubbornly tried all other combinations too. And switched between having my HMD display as primary or secondary. And swapped the layout around in the Windows Display Settings... but no matter what, the compositor won't budge.

Anything else I can try?

**Comment by TheDeveloperGuy** [comment]
Looks like you're getting the window position or size wrong. Try getting it working on an HDMI monitor first, then apply your technique to the HMD. Unless your EDID is already whitelisted (ie. you spoof one from an Oculus, OSVR or HTC headset), it probably won't help providing it to OpenVR for "direct mode".

**Comment by codalyn** [comment]
"Looks like you're getting the window position or size wrong."

But what the heck is the "right" window position / size then? I'm passing in the size and position that Windows itself says this monitor has. Shouldn't that be "correct"?

The display I'm using **is** a simple HDMI monitor for all intents an purposes at the moment. I can see my Windows desktop duplicated on it.

I'm not even trying to get "direct mode" working at the moment (though the whitelisting is only relevant for nVidia; AMD will work with any display, so long as the EDID is valid -- I asked).

**Comment by TheDeveloperGuy** [comment]
It should. If all the things that should work on computers worked, we'd be about 30 years into the future from where we are now. Do you have another (apart from your main) monitor to try getting extended mode working? This will rule out any peculiarities that may be specific to your HMD...

**Comment by JoeLudwig** [comment]
@TheDeveloperGuy wrote:
> If all the things that should work on computers worked, we'd be about 30 years into the future from where we are now. 

I suspect you'll be able to make the same statement in 2047. :)

@codalyn Can you post a full system report somewhere? That will let us see the displays on your systems as well as the full logs.

**Comment by codalyn** [comment]
@JoeLudwig Will do. I'm working off-site Today, but I'll post a full systems report tomorrow.

**Comment by codalyn** [comment]
@JoeLudwig Here's my system report: https://www.dropbox.com/s/mh2f637dyi2s98n/codalyn_system_report.txt?dl=0

My "HMD" is \\.\DISPLAY2 (with display rect 2160x1200 @ (-2160, 0))

Let me know if there's anything else you need.

**Comment by JoeLudwig** [comment]
@codalyn What is your driver returning from GetWindowBounds?

**Comment by codalyn** [comment]
@JoeLudwig x = -2160, y = 0, width = 2160, height = 1200

**Comment by codalyn** [comment]
Solved it!

Or, rather, found a workaround: apparently, the compositor doesn't like if if the window position has **negative** coordinates. If I rearrange the displays so that my HMD has positive coordinates. the driver works and the compositor initializes successfully!

I facepalmed a lot when I found out...

@JoeLudwig Bug in the compositor then?

**Comment by cjlong1213** [comment]
@codalyn 
Hi, codalyn.
If do not rearrange the displays can we show compositor window to HMD display at extended mode?
I have two displays and both with resolution of 1680x1050, I want show the compositor window to the second(HMD) display,but failed.
Function IsDisplayOnDesktop() return TRUE and IsDisplayRealDisplay() return TRUE.
Below are my default.vrsettings:
{
   "driver_sample" : {
      "enable" : true,
	  "monitor" : "DELA09C",
	  "supersample" : 1,
	  "edid_vid" : 44048,
	  "edid_pid" : 41116,
	  "directMode" : false,
      "serialNumber" : "1234",
      "modelNumber" : "SampleModel 1",
      "windowX" : 1680,
      "windowY" : 0,
      "windowWidth" : 1680,
      "windowHeight" : 1050,
      "renderWidth" : 1680,
      "renderHeight" : 1050,
      "secondsFromVsyncToPhotons" : 0.011,
      "displayFrequency" : 60.0
   }
}
Do you have any guidance?
Look farward to your feedback and thanks in advance~

**Comment by codalyn** [comment]
@cjlong1213 Have you compared the window X/Y/width/height settings in your default.vrsettings to where the OpenVR system thinks that monitor is located on the desktop? I.e. create a systems report for your machine and check that the values match. I've found the compositor will work [with _my_ custom driver that is -- I'm not using the sample code provided with the SDK] _if_ the window X/Y/width/height match exactly (and don't contain negative values for the position).
