### ISSUE TITLE
How to use intel hd graphics to support direct mode

### ISSUE THREAD

**Issue by HelenXR** [ValveSoftware/openvr#451]
The VR-ready machine is only 1%, we urgently hope that openVR can support Intel, integrated graphics, integrated graphics of the performance of Intel is very limited, but we still hope to be able to directly support the rendering mode, only to watch the video.

**Comment by TheWhiteAmbit** [comment]
you don't

**Comment by Balderick** [comment]
That is why they HelenXR is asking.


https://youtu.be/sv_AVI9kHN4. This video goes into great detail of how to use integrated Intel HD GPU for Five

We need to remember Valve want VR to work on a far wider range of hardware than what proprietary drivers officially support.   This is because amd and nvidia gave false hope about supporting a wide range of hardware with their new APIs.

Nvidia and amd let a lot of people down after removing sli, multi GPU support and vr support for their new APIs.   This was simply to force folks into buying a new GPU or a new PC for vr support.

A lot of early vr support in games like team fortress and half life still run on far older GPUs than a gtx 970

Many vr supported titles also have a mobilevr port which helps with running on older hardware on PC too.  i.e. Inmind

This guy tried to run steamvr on an older Intel HD integrated GPU. https://youtu.be/sv_AVI9kHN4

**Comment by TheDeveloperGuy** [comment]
AFAIK there is no "direct mode" in Intel's drivers (being that they rightly don't market them as VR-ready drivers). That said, there's no reason why they can't be used in "extended mode" for less demanding VR software.

**Comment by Balderick** [comment]
Maybe Intel project alloy devices do not even need direct mode at all?

AFAIK direct mode is really an oculus platform feature.   Steamvr added direct mode support purely to allow rift/dk users access to all steamvr content.

**Comment by TheDeveloperGuy** [comment]
"Direct mode" in this context refers to a nVidia and AMD driver feature that allows for HDMI displays that can display content that is uncoupled from the Windows monitor topology. It's a convenience and performance enhancement that benefits all (HDMI) HMDs, it was merely initiated by Oculus as they were first out the gate with a (popular) HMD. The reason why it's not in Intel's drivers (yet) is because they're no good for VR so why market them as such. At some point (soonish?) the "direct mode" APIs will be incorporated into Windows and won't depend on particular GPU drivers. Check out godbyk's posts in OSVR for more info on this (MS has been saying "soon" since 2015)...

**Comment by TheDeveloperGuy** [comment]
The key here is understanding that there is an unfortunate naming convention going on. "Direct mode" as it is meant here, and as it is meant by "VR-Direct" is a way of hiding an HDMI monitor from Windows (it otherwise is the same as "Extended mode", it's just freeing up any software using it from trying to figure out its co-ordinates in the Windows desktop system). The "Direct Mode interface" which the IVRDriverDirectModeComponent represents is a way of talking to Oculus HMDs in OpenVR without bypassing Oculus' own compositor. Effectively it's a way of using an existing VR API (eg. Oculus) from within SteamVR. If you don't have an existing VR API, then you would effectively need to write your own mini-Oculus runtime. "Direct Mode" and "Direct Mode interface" are fundamentally two separate concepts.

**Comment by Balderick** [comment]
Windows Creators update starts rolling out today.

**Comment by TheDeveloperGuy** [comment]
OSVR != OpenVR

**Comment by nikhilchandwadkar** [comment]
Apologies, I mistook this for an OSVR issue thread. Had a couple of tabs open, posted in the wrong one.

**Comment by crozone** [comment]
Not to necro this issue, but the lack of Direct Mode on Intel GPUs causes issues with dual-GPU setups where the Intel GPU still handles all monitor output.

This is common in notebooks (like the Surface Book 2 15"), where an NVIDIA GPU will render all frames, but then copy them to the Intel GPU for displaying externally. The lack of Direct Mode on the Intel GPU forces this setup to use the Extended monitor compositor mode, which causes some pretty severe performance issues.

Given that Windows MR is certified as "Ultra" under this configuration, the Intel driver *must* have a Direct Mode equivalent, because Microsoft is using it right now for MR.
