### ISSUE TITLE
What is Prop_DisplaySuppressed_Bool supposed to do?

### ISSUE THREAD

**Issue by TheDeveloperGuy** [ValveSoftware/openvr#453]
I was trying to get rid of 'extended mode' warnings in my driver and came across this property (which didn't help BTW). It seems if the HMD driver sets this to true it disables the SteamVR dashboard. It would be useful to understand what this means...

**Comment by JoeLudwig** [comment]
This property is used in drivers like the Oculus driver to let the rest of the system know that its output isn't going to the display. In the case of the Oculus driver this happens when the user presses the Oculus button or switches to another application.

At the moment the only effect of the property is to disable the dashboard. We will likely use it for other things in the future as necessary.

**Comment by TheDeveloperGuy** [comment]
@JoeLudwig Thanks!
