### ISSUE TITLE
Fail to create my own hmd driver.

### ISSUE THREAD

**Issue by osbike** [ValveSoftware/openvr#51]
I tried to add my hmd driver according to steps in Wiki.
I implemented driver factory function, IClientTrackedDeviceProvider and IServerTrackedDeviceProvider  and then put the DLL to drivers folder and execute hellovr_opengl for testing my DLL.

But the problem is that I can see only HmdDriverFactory and BIsHmdPresent were called in my dll.
And then it showed "Unable to init VR runtime: Hmd Not Found" dialog.
Could anyone provide more detail step to implement a hmd driver?

Sorry for this rookie question, I don't quite understand the flow, and appreciate for any comment.

**Comment by JoeLudwig** [comment]
Did you return true from BIsHmdPresent?

The next SDK update will include a sample driver as a starting point. That should help you out significantly.

**Comment by osbike** [comment]
Thanks for the reply, Joe.

Yes, I return true from BIsHmdPresent.
I expect that init function be called from somewhere, but nothing happened.

Is there a date for the update?

**Comment by yhnchang** [comment]
I was running into the same issue on PC. After some debugging, I noticed that when my `HmdDriverFactory()` is being called, the supplied `pInterfaceName` is `"IClientTrackedDeviceProvider_003"`. However, the current version (0.9.15) of openvr_driver.h has `IClientTrackedDeviceProvider_Version = "IClientTrackedDeviceProvider_002";`, thus my `HmdDriverFactory()` function always returns InterfaceNotFound. When I override the provider version and return my own `IClientTrackedDeviceProvider`, it simply crashes.

It appears the problem is that the class declarations in openvr_driver.h is outdated. @JoeLudwig can you please help us update the header file to match the latest runtime? Thanks!

**Comment by JoeLudwig** [comment]
Opt-out of the beta to fall back to the old API.  We'll get the new build flipped over and an SDK shipped soon, but in the meantime just opt-out of the beta.

**Comment by yhnchang** [comment]
I opt-out of the beta and it's working now. Thanks!

**Comment by osbike** [comment]
I already opt-out of beta, but I still meet my previous problem.
After BIsHmdPresent() returned true, nothing happened.
Could anyone help? Thanks lots.

**Comment by osbike** [comment]
I found I misunderstood the flow, and GetTrackedDeviceCount returns 0.
It is working now. Thanks !
