### ISSUE TITLE
Features request: Support Android VR in "null" driver

### ISSUE THREAD

**Issue by r57zone** [ValveSoftware/openvr#512]
Add to "null" driver (or its copy, Android-Null-Driver) support for head tracking from Android application [FreePie IMU](https://github.com/Xtreamer/FreePie-DiyHt/blob/master/Lib/Android/com.freepie.android.imu.apk) (better) or [Wireless IMU](https://play.google.com/store/apps/details?id=org.zwiener.wimu).

With [config](https://pastebin.com/raw/5cgpRe6n) i can get a [stereo image](https://imgur.com/a/0wTjb) (for streaming to Android smartphone) on desktop screen, but i can't head tracking.

To head tracking in null driver, you need to add reading from UDP port 5555 [data from the FreePie IMU](https://github.com/Xtreamer/FreePie-DiyHt/blob/master/Lib/Android/FreePIE%20Android%20IMU/src/com/freepie/android/imu/UdpSenderTask.java#L149) (accelerometer, gyroscope, magnetometer) to calculate quaternion HMD orientation (6 dof).

Or wireless IMU example UDP packet:
890.71558, 3, 0.076, 9.809, 0.565, 4, -0.559, 0.032, -0.134, 5, -21.660,-36.960,-28.140

Timestamp [sec], sensorid, x, y, z, sensorid, x, y, z, sensorid, x, y, z
Sensor id: 3 - Accelerometer (m/s^2); 4 - Gyroscope (rad/s); 5 - Magnetometer (micro-Tesla uT);

Thanks.

**Comment by TheDeveloperGuy** [comment]
This is what is known as an "exercise best left to the reader". You will never reach the performance level needed by using desktop window capture and 3rd party sensor apps broadcasting over UDP. That said, it would be a good learning experience if you're looking at becoming a more experienced developer to implement such a thing yourself. I'd recommend using the IVRVirtualDisplay interface rather than the IVRDisplayComponent interface as a starting point (at least then you won't have to figure out the intricacies of window capture etc.).

**Comment by JoeLudwig** [comment]
The null driver itself isn't the place for this kind of feature. The sample driver in the SDK is basically a copy of the null driver, so if you want to create your own driver that has this functionality, please feel free.
