### ISSUE TITLE
How to determine if a particular SteamVR installation supports a certain SDK level?

### ISSUE THREAD

**Issue by TheDeveloperGuy** [ValveSoftware/openvr#550]
My HMD driver has multiple code paths (it can support all HMD types). I want to use the "driver supplies vsync" property in the latest (1.08) SDK. How can I tell whether the user's SteamVR installation supports that property? If I assume that it does (user has received all SteamVR updates), then how can I cater for the scenario where they have been offline and missed the updates?

**Comment by Balderick** [comment]
> How can I tell whether the user's SteamVR installation supports that property?
Would a user of a device that uses drivers that does not support 1.0.8 just see "Not Ready" error 308, 203 or such?

**Comment by TheDeveloperGuy** [comment]
Probably not. The scenario that I'm asking about is that the HMD driver can request new features that are not (yet) in the user's SteamVR installation (ie. the driver is more recent than SteamVR, not the other way around). In general SteamVR is backwards-compatible, so (unless they're very old - to my knowledge nothing fits this category yet) any features that the driver is using will continue to be able to be used in later SteamVR versions without needing to update the driver. If an existing driver fails to work in a newer SteamVR installation it is most likely a bug in the driver. 

That said, the latest SteamVR versions have a "feature" where they will fail initialisation (HMD not present) based on a check for USB PID/VIDs. The way this "feature" was sold is that it can speed up detection, not that it would kill SteamVR if it couldn't find the USB device. That may have been a misunderstanding, who knows, not enough documentation.

**Comment by JoeLudwig** [comment]
Except in some exceptional circumstances (like an enterprise where an IT department is tightly controlling updates) a given SDK version should be supported by all user's installations. That's why SDK updates always come after a beta is published out to everyone. We wait to push the SDK until the users get the new runtime. You could call VR_GetGenericInterface on an interface version that's only in the new SDK. It's much better to just get the user to go online and let the update download than to try to write fallback behavior into your app, though.

Drivers should be backward compatible just like apps, but obviously bugs can happen. If you find a beta update has broken your driver, please let us know ASAP. (There have been a few breaking changes that required some drivers to update, but they've been few and far between lately.)

I'm not sure what you're saying about failing initialization based on the USB VID/PID checks. Drivers specify which USB devices are associated with that driver in their driver.vrdrivermanifest file. That can be a wildcard if the driver always wants that check to pass. The change to using a manifest entry instead of a client-side driver wasn't so much for speed as stability. It used to have to load every driver into every application process which is problematic for a bunch of reasons.

**Comment by TheDeveloperGuy** [comment]
So, the gist is don't worry about it and if your reliance on something that isn't there breaks the proper working of the driver, you can't know, but the user should in all instances be smart enough to go online and update SteamVR if it suddenly starts misbehaving? Sounds like extra support work (because if something is even vaguely possible lots of users will do it in my experience)... At least I know what to tell them now! :)

Isn't there a way to tell if a property can be set? Seems like there could/should be. 

I took the USB VID/PID to be a way for OpenVR to do an easy check on whether a device is present, not to do an HMD not present error and call Activate() anyway, but then never send the driver frames (which is what happens with the latest SteamVR, but only on some machines). The behaviour of calling Activate() regardless of whether the VID/PID was present and using the results of that to determine whether the HMD was present is how it works on most machines with latest SteamVR and on all machines up to quite recently. My HMD can be USB or wireless (Oculus or Virtual mode) so sometimes the USB device is not present. (Not) Funnily enough the USB check fails on those machines that fail now, even when the device is connected via USB! So I changed the manifest to not include USB VID/PID and all is well...

**Comment by TheDeveloperGuy** [comment]
In the instance of the particular property I'm asking about, I guess the wise move would be to wait a while before implementing it, if I think it's going to cause me problems. I guess there must be some Steam timeout on how long a user can stay offline before having to go back on (and hence updating). I'll look that up :)
