### ISSUE TITLE
Why Should OpenVR Driver Authors Compile Their Drivers For Steam Runtime?

### ISSUE THREAD

**Issue by Balderick** [ValveSoftware/openvr#581]
Valve devs have suggested, hinted and described that compiling openvr drivers for steam runtime resolves many issues.

AFAIK the sixense SDK and hydra drivers provided by Valve through steam store are the only openvr drivers that have been compiled for steam runtime.

Why should openvr driver authors compile their openvr drivers for steam runtime?

**Comment by shensheng27** [comment]
how compiling openvr drivers for steam runtime and what benefits？

**Comment by Balderick** [comment]
Openvr apps, drivers and utilities can be compiled for steam runtime by means of steamworks SDK.  https://partner.steamgames.com

http://store.steampowered.com/app/491380/SteamVR_Driver_for_Razer_Hydra/ is an example of one openvr driver being compiled for steam runtime.


In other issues discussing things ranging from juddering, misbehaving tracking, common server crashes and starting errors Valve devs have hinted at openvr drivers being compiled for steam runtime would help.   

It would be good if somebody could elaborate on what benefits this does actualy bring.    Valve seem to be only provider of openvr driver compiled for steam.

**Comment by TheDeveloperGuy** [comment]
Wherever this information comes from, it is either being misunderstood or misrepresented. OpenVR drivers are compiled against the OpenVR SDK. There is no SteamVR SDK. Anyone saying that their driver's "juddering, misbehaving tracking, common server crashes and starting errors" is due to "not being compiled for steam runtime", is misrepresenting the cause of a bug in their driver. 

I can confirm that my driver (compiled with the OpenVR 1.08 SDK) does not have any of these issues, and knowing what I do about OpenVR/SteamVR I would say that there is only one way for a driver to talk to SteamVR and that is via the OpenVR SDK.

It may be that to integrate a driver with the Steam Store you need to add the SteamWorks SDK, but that would certainly not cause SteamVR stability issues (unless that integration was implemented incorrectly, and definitely not if there was no SteamWorks SDK integration).

**Comment by Balderick** [comment]
> Wherever this information comes from, it is either being misunderstood or misrepresented. 

Possibly,  I could be highlighting something that is being overlooked and underestimated also.

**Comment by TheDeveloperGuy** [comment]
@Balderick No, you are speaking gobbledygook... ;)

SteamVR is the only implementation of OpenVR. There is no other way (at this time) to run OpenVR applications.

The only thing that is possible is that you are referring to very old documentation where there was a SteamWorks VR API. That was dropped at least 2 years ago.

https://github.com/ValveSoftware/steamworks-vr-api

**Comment by Balderick** [comment]
I understand that you do not get what I am trying to ask.

Here is an example of where a Valve dev more than hints at driver compiled for steam runtime ( not steamvr, not openvr but steam runtime) and setting a context of when this would be helpful is found at https://github.com/ValveSoftware/openvr/issues/566#issuecomment-310773217

**Comment by TheDeveloperGuy** [comment]
@Balderick I understand that you do not (can not?) get what I'm telling you, which is the answer to your actual question.

You are misunderstanding a discussion of a Linux-specific build environment for something else... ;)

**Comment by TheDeveloperGuy** [comment]
@Balderick In particular, your assertion that there is some secret way of compiling drivers so that they don't crash is completely incorrect. There is no secret way of compiling drivers. You build them against the OpenVR SDK and that's it. If the driver has stability issues, that's the driver's fault.
