### ISSUE TITLE
There is no event based API. Something like OnNewPose

### ISSUE THREAD

**Issue by chipweinberger** [ValveSoftware/openvr#601]
A modern API should not rely on polling as its only means to get new poses.

**Comment by echuber2** [comment]
There is a new pose every moment so firing an event for that would require constantly polling for the event. It's like polling for a new frame.

**Comment by chipweinberger** [comment]
Not sure I understand what you mean. For most uses, polling is the correct API to use. I agree.

There are some more niche uses where you want to be notified of every new pose (drawing applications, for example).

**Comment by echuber2** [comment]
I thought you were implying that significant time would pass in which there was _not_ a new pose. It seems your point is different. If you want to try to get around the whole video issue and just get poses, I think you can do that. http://steamcommunity.com/app/358720/discussions/0/361787186419244897/#c361787186420927052
If you need to cut through a latency issue you may also want to google for PostPresentHandoff.

The suggested loop with WaitGetPoses is not this simple because of how the poses need to be synced to the view. If you watch the GDC videos, the way they block and wait for poses and then try to make sure the poses are accurately synced and predicted for the final display is very complicated. It's not necessarily desirable to get poses that are out of sync with the prediction, but at any rate, the entire video submission process is gated by WaitGetPoses and there's no way around all this syncing and blocking in the runtime.

I think just turning the new poses into another event to poll for would be an antipattern given the intended usage. Just my two cents

**Comment by chipweinberger** [comment]
Yes a dedicated thread that just calls with waitGetPoses could work. But if I have no video data, would that still work, given you're saying they wait for some video syncing too?

**Comment by echuber2** [comment]
I don't know what you're trying to do exactly. Usually a SteamVR application should use WaitGetPoses to get poses for the current frame being rendered; WGP also releases images to the HMD, so there's no way around using WGP if you need the HMD to display images at all. You should call WGP in your main render thread.

Read these:
http://steamcommunity.com/app/358720/discussions/0/152391285460288350/
http://steamcommunity.com/app/358720/discussions/0/385429125016008605/

Also watch the GDC 2015 and 2016 videos for details on the prediction and rendering loop.
https://www.youtube.com/watch?v=JO7G38_pxU4
https://www.youtube.com/watch?v=DdL3WC_oBO4

If you are doing something unusual in which you do not care about sending images to the HMD, but only want to track the device poses at a high rate in some desktop app, then you can do that in another way using GetDeviceToAbsoluteTrackingPose and NOT WaitGetPoses.
http://steamcommunity.com/app/358720/discussions/0/361787186419244897/#c361787186420927052

**Comment by LoSealL** [comment]
Getting new pose is more likely a passive API. There is always new position streaming out of the sensors, however your render pipeline works much more slowly. Hence all you need is a very recent position right before you render your frames, so you just need to call WGP before your rendering.
In fact, if you use Unity or Unreal plugin, you don't need anything detail...

**Comment by chipweinberger** [comment]
For my use case
