### ISSUE TITLE
ShowKeyboard causes InputFocus event

### ISSUE THREAD

**Issue by JashanChittesh** [ValveSoftware/openvr#647]
We're using the SteamVR / OpenVR keyboard in our game, roughly based on the example [KeyboardSample.cs](https://github.com/ValveSoftware/openvr/blob/master/samples/unity_keyboard_sample/Assets/KeyboardSample.cs). I'm on the SteamVR beta, built Oct 14, 2017, version 1507941678.

Unfortunately, when the keyboard opens, OpenVR sends the InputFocus event which results in our game pausing. I think I can work around this by not listening for this event while messing with the keyboard but that's really a hack with nasty side effects (what if a player opens the dashboard when they have the keyboard open in the game?)

I believe when an application or game opens that keyboard, no InputFocus events should be fired.

**Comment by JoeLudwig** [comment]
In the current SDK "input focus" and "the app should pause" are somewhat conflated. There are changes in the works to detangle those two things. The keyboard needs to capture focus to get all the clicks, though, which is why you're getting these events.

Until the more granular checks arrive in an SDK, I would suggest you do your hack. You can fix the "dashboard opened while keyboard is up" case by looking for VREvent_KeyboardClosed. That should be sent to your app as the dashboard comes up (because active keyboards are cancelled when the dashboard comes up.) If you get that event and IVROverlay::IsDashboardVisible returns true, you should pause.
