### ISSUE TITLE
Pitch rotation in euler goes from +80 to -80 degree?!

### ISSUE THREAD

**Issue by TobiMiller** [ValveSoftware/openvr#689]
Hey guys,

i want to track the controllers in my robotic application. I get the 3x4 matrix (rot+trans). I calculate the roll, pitch, yaw with some tools (ROS TF - if you know it) but also did it by myself with following code (both gave me the same result):

```
sy = math.sqrt(mPose[0][0]**2 +  mPose[0][1]**2)
yaw = math.atan2(mPose[1][2],mPose[2][2])
pitch = math.atan2(mPose[0][2], sy)
roll   = math.atan2(-mPose[0][1], mPose[0][0])
```

**My problem:** One axes goes from 0 to ~80 and than back to -80 degree but i dont change rotation direction.

i have no clue. is your rotation matrix something special what i dont know from robotics and is known in 3D software development?

hope somebody can help me :)

**Comment by echuber2** [comment]
I'm not sure your calculations are correct for the standard being used in OpenVR. Here are some more details about it, and I hope you can rework the calculations. I believe the 3x4 pose matrix is indexed like this:

matrix[row][col]

So it is row-major. In addition, OpenVR is assuming the OpenGL conventions for 3D: a right-handed coordinates system, where if you are standing at the origin, +X is to your right, +Y is straight up, and -Z is forward.

If this is too much of a pain to debug based on calculations direct from the pose matrix, remember that you always have this method of finding the angle between two 3D vectors: just use dot(a,b)/(|a|*|b|) = cos(theta) to figure out the rotation angles manually and ensure that the ranges and offsets are what you expect.

**Comment by echuber2** [comment]
To elaborate, if you study the hellovr example project, particularly UpdateHMDMatrixPose and ConvertSteamVRMatrixToMatrix4, you can see how they're converting the SteamVR 3x4 pose matrix to the Matrix4 class. The Matrix4 class is stored in column-major format and I think it can only be indexed by one index. The SteamVR 3x4 matrix obtained from WaitGetPoses should be a viewspace-to-worldspace transformation, but in UpdateHMDMatrixPose they convert it to a Matrix4 and also take the inverse, saving m_mat4HMDPose as a worldspace-to-viewspace transformation.

With this in mind, the SteamVR 3x4 matrix must be like this, where X=camera right, Y=camera up, Z=camera back (= -forward), and P=position:
[ X1 Y1 Z1 P1 ]
[ X2 Y2 Z2 P2 ]
[ X3 Y3 Z3 P3 ]

Then I believe the pitch-up angle in radians would be asin(-Z2), and so on.

In addition, if you are ever seeing numerical values seem to be clipped in the <-80 or >80 degrees range when you expected +-90, it suggests that you're having numerical instability near the extremes of the trig function. If you need a lot more precision then you may need to switch to a more robust math library or use the dot-product and cosine method I mentioned above to find the angle to a different axis of reference, then adjust the result as necessary.

**Comment by TobiMiller** [comment]
@echuber2 

can be closed. was my fault. shame on me. i rotated the controller in its own coordinate system and not in the lighthouse/world one. 
Where is the documentation about these conventions? maybe a sketch would be helpful.

**Comment by echuber2** [comment]
@TobiMiller Since you created this issue, you have the power to close it yourself :-) (I can't do that, I'm just a normal user here...)

About the documentation, I agree the OpenVR/SteamVR documentation needs a lot of work. There is some documentation here on GitHub but it's not complete and some of it isn't up to date. The best documentation available right now is the code comments in the examples provided, in particular, studying the hellovr project carefully will be helpful. About the matrix conventions, some of this assumes prior knowledge of OpenGL; I think the SteamVR team assumes people are coming from a games programming/OpenGL background, not necessarily a robotics background, so I can't say there will be similarities with ROS necessarily. As noted, there are several different conventions in use here for the matrices even within hellovr (row-major vs. column major storage, several matrix data types, and working with an affine matrix in its inverted or uninverted form). It would be helpful to have a unified intro document from the community to clarify all the discrepancies, but I don't have time to contribute one myself right now unfortunately.

This article explains the concept of the model-view-projection matrix pipeline in general. http://www.opengl-tutorial.org/beginners-tutorials/tutorial-3-matrices/
They are using the free glm library for the matrix data types in use. glm is a nice library to use and it's designed to be compatible with OpenGL. Note that hellovr doesn't use glm, but instead uses a combination of these:

Matrix4 by Song Ho Ahn - also a nice library
http://www.songho.ca/opengl/gl_matrix.html

So-called "SteamVR matrix" types, e.g. HmdMatrix34_t, defined in openvr.h
(These are ordinary C structs with static float arrays!)

If you study hellovr, you'll see that the API natively delivers poses to you in TrackedDevicePose_t objects through WaitGetPoses(). This object type is a struct containing a HmdMatrix34_t. In hellovr, they use ConvertSteamVRMatrixToMatrix4 to get this into a nicer Matrix4 object that is easier to work with. But in addition, UpdateHMDMatrixPose() inverts the matrix when storing it as m_mat4HMDPose internally! This is done to get it into the expected "view" matrix configuration as described in the model-view-projection article above. And it's used in that way in the function GetCurrentViewProjectionMatrix(), multiplied with the projection matrix as is conventionally done in OpenGL. This is how the format of the pose can be deduced.
