### ISSUE TITLE
Update driver-side API to newest version

### ISSUE THREAD

**Issue by matzman666** [ValveSoftware/openvr#709]
The lighthouse and oculus device drivers contained in the newest SteamVR update use a newer version of the driver-side API than currently available via this repository. Specifically the drivers now use interface*IVRServerDriverHost_005* while this repository still only contains interface *IVRServerDriverHost_004*. To get [OpenVR Input Emulator](https://github.com/matzman666/OpenVR-InputEmulator) working with the newest SteamVR version I require the interface specification for *IVRServerDriverHost_005*, so please update.

**Comment by JoeLudwig** [comment]
There will be an updated SDK in the next few days to match the new image. 

We don't support any sort of version-safe compatibility for drivers that hook vrserver itself. In fact, somewhere down the road each driver will move into its own process and this approach will stop working entirely.

What are you trying to do? Maybe we can provide an API that lets you do that without hooking?

**Comment by matzman666** [comment]
> What are you trying to do?

What I am doing is hooking into the IVRServerDriverHost interface to manipulating pose updates and controller events send from the drivers for several reasons, e.g. for motion compensation for motion simulation platforms, adding offsets to the controller poses, impersonate a vive controller with my DIY gun controller (arduino connected to a vive tracker), input remapping and other advanced input handling features. But currently the most sought-after feature is some FO4-specific fixes for Oculus Touch users. That's why I currently have a large number of disappointed users who want to play Fallout with their Rifts but cannot.

> Maybe we can provide an API that lets you do that without hooking?

That would be great to have some official APIs for manipulating device poses and input events.

> In fact, somewhere down the road each driver will move into its own process and this approach will stop working entirely.

I am already making plans to move the hooking from the driver-side to the application-side. I started doing it on the driver-side because in the early days of VR there was too much of a version chaos on the application-side, but now that version chaos has mostly gone away. But moving it to the application-side takes some time, so in the near future I will still doing it on the driver-side.

**Comment by Balderick** [comment]
Wasn't there an additional  beta channel frozen for CES ?   


Ooh look at that.  https://steamcommunity.com/games/250820/announcements/detail/1584570207554706656

Nice one, guys.

**Comment by gb2111** [comment]
@JoeLudwig 
Same for me. For example I use this method to extend virtual range of controller move if a person has very limited due to disability.
Looking forward,
Greg

**Comment by 3DRSenior** [comment]
@JoeLudwig 
Same for us at 3dRudder, you changed IVRServerDriverHost_004 to IVRServerDriverHost_005 (6 less virtual fonction, look like linked to the pad and to the axes) and you added IVRPaths_001 with a batch system, look like ... but i am not sure i can go farter without the update of the openvr_driver.h and few documentation ...  
Thank you

**Comment by 3DRSenior** [comment]
@matzman666 

> I am already making plans to move the hooking from the driver-side to the application-side. I started doing it on the driver-side because in the early days of VR there was too much of a version chaos on the application-side, but now that version chaos has mostly gone away. But moving it to the application-side takes some time, so in the near future I will still doing it on the driver-side.

I started to do the same but i am afraid that it will be see by some app as an cheat / hack ... and may ban the user ...  it look safer to do it at the driver level for this raison ...  

@JoeLudwig
> Maybe  we can provide an API that lets you do that without hooking?
Yes indeed, this could be the way :)

**Comment by gb2111** [comment]
Hi,
I tested official SteamVR with RiftCat and Oculus. Seems like for Oculus hooking does not work.

Right now I can play VR with person with Cerberal Palasy or after Stroke after I remap his ability to move. So for example he or she does not need to look down where actual hand is. Also movements can be extended. On this photo guy is looking with comfort forward, not where his hand is. Also orientation and range is modified. I am supporting him with gamepad. Please ensure there is way I can make it working.

![firefox_2018-01-09_18-52-28](https://user-images.githubusercontent.com/22025896/34735166-c84c4bde-f56e-11e7-843a-9ae124170426.png)

Greg

**Comment by matzman666** [comment]
> I started to do the same but i am afraid that it will be see by some app as an cheat / hack ... and may ban the user ... it look safer to do it at the driver level for this raison ...

That's true. I mostly play single-player games, and therefore forget how well-protected some multi-player games are. The reason I want to move to the application-side is (1) for some things like e.g. motion compensation the pose manipulation is better done after motion prediction, (2) it is easier to implement game specific fixes and keeps the GUI cleaner, and (3) to avoid problems like this thread is about because applications are less likely to use yet-to-be-released APIs than drivers.

> I tested official SteamVR with RiftCat and Oculus. Seems like for Oculus hooking does not work at all even if I use only one hook for pose update. These method is not called for oculus devices in way I can use it.

It also does not work with [the new branch](https://steamcommunity.com/games/250820/announcements/detail/1584570207554706656) Valve released? Oculus users have told me that Input Emulator works with this branch, so it should also work with your application when it worked with the previous non-beta SteamVR version.

**Comment by JoeLudwig** [comment]
> applications are less likely to use yet-to-be-released APIs than drivers
Yeah, the Oculus and Lighthouse drivers are pretty much guaranteed to be using not-yet-released APIs whenever those things exist. They all build at the same time from the same tree.

The new input system will allow rebinding of poses (after prediction) and any button or scalar value state to any other button or scalar value. Most of the infrastructure for this is in place now, and the dashboard is using the new system. We're hoping to get the user-facing interface and the application side API out soon.

@matzman666 : The new SDK will be out later today. In the meantime, the documentation is up for the new driver input API that you'll need to hook to continue to do this sort of operation.  You might want to make your code extra clever so it can run against both the openvr-inputemulator-temporary beta and the default build. Otherwise people are going to get awfully confused as new builds ship.

New driver input API docs are here: openvr-inputemulator-temporary

**Comment by gb2111** [comment]
@matzman666 @3DRSenior 
I had this kind of accusations when I released my driver. 
Then contacted few developers from online games asking if they see any problem with WalkinVR and they had nothing against potential risk caused by my driver. They said that they must protect online game 100% from such situations and our case is really not worst thing they worry about.

Greg

**Comment by gb2111** [comment]
@JoeLudwig , does rebinding of poses (after prediction) mean we can influence position of devices ? Sorry, it is my English.

Greg

**Comment by JoeLudwig** [comment]
By "rebinding poses after prediction" I mean you can make relative small adjustments to the position of the user's hands in-game to account for different controller types. This should work fine for rotating hands for disabled people. 

It's not likely to work that well for moving the whole coordinate system to simulate moving around in the room. We'll need to think some more about that.

BTW, the new SDK is available now: https://github.com/ValveSoftware/openvr/releases/tag/v1.0.12

**Comment by gb2111** [comment]
@JoeLudwig
For moving around the room the existing mechanism is perfect and don't need hooking.

Regarding controller position, what you say does not mean like something that might solve problem if small will be not enough. 
Let me give you the simplest example. For Spinal Muscular Atrophy you cannot raise hands due to weak muscles. In this case I am lifting up controllers virtually by 30 or 40 cm which is not relatively small amount. But this give ability to play with comfort looking forward and not down where they are. This relatively simple thing makes big difference.
Please check [this video](https://www.youtube.com/watch?v=NnjUe7PL-cs), especially first girl and then boy at the end then you will know what I mean.

Looks like now VR is designed for healthy people where physical to virtual movement is one to one. 
This is most obvious and natural intuition but once you notice that it does not have to be the case the possibilities open for very huge amount of people. I will be posting some interesting videos shortly.

Thanks again for your answer and I am very happy to continue this conversation.
Greg

**Comment by JoeLudwig** [comment]
Yeah, the binding system isn't going to help with that kind of application. You'll need to continue to do whatever you're doing now. (Pose offsets in the new binding system are constant.)

If changing the driver interface is breaking you, that means whatever you're doing isn't supported by our version-safe backward compatibility. We'll likely need to add a mechanism that allows one driver to filter the poses from another driver before they're applied in the system. Then you could that system for both lifting up controllers and moving around in space.

**Comment by gb2111** [comment]
Thanks. 
Only Oculus stopped working what I have observed long time before in Beta. There was no crash so version mechanism works. However for some reason I misunderstood situation completely... So if I continue testing Beta regularly there should be no problems.

Thanks for support,
Greg
