### ISSUE TITLE
macOS: How to get texture handle from shared handle passed to passed to IVRVirtualDisplay::Present()

### ISSUE THREAD

**Issue by TheDeveloperGuy** [ValveSoftware/openvr#747]
On Windows the following code is used:

		ID3D11Texture2D *pTexture
		device->OpenSharedResource((HANDLE)backbufferTextureHandle, __uuidof(ID3D11Texture2D), (void**)&pTexture);

How does one get the texture handle on macOS and what does it represent? The only information I have on this is "The texture format is currently an IOSurfaceRef, so an MTLTexture needs to be created that is backed by an IOSurface."?

**Comment by natbro** [comment]
if you are calling `IVRCompositor::Submit` on macOS, you can submit `TextureType_OpenGL` or a shared texture handle on macOS which is conveyed via

    TextureType_IOSurface = 3, // Handle is a macOS cross-process-sharable IOSurfaceRef

if you are drawing with openGL you can just submit the gltex id directly and it will be copied into an IOSurface - we need to get the data into a cross-process capable IOSurface in order to inexpensively utilize the texture across processes to the vrcompositor. If you want to avoid the overhead of GL/IOSurface interop and for now to avoid the copy or if you are using Metal, you can pass in an IOSurfaceRef directly. For any other OpenVR APIs using `SharedTextureHandle_t`, on macOS this should also be an IOSurfaceRef that you have drawn to in whatever way you choose - you can do this with CoreImage, with AVFoundation decoding, with OpenGL, or with Metal. Feel free to google drawing on IOSurfaces from those APIs and extracting the surface- I'll just give a Metal example:

    IOSurfaceRef iosurface = IOSurfaceCreate( @{(id)kIOSurfaceWidth:@(width), (id)kIOSurfaceHeight:@(height), (id)kIOSurfaceBytesPerElement:@(4), (id)kIOSurfaceIsGlobal:@YES} );

    MTLTextureDescriptor *desc = [MTLTextureDescriptor texture2DDescriptorWithPixelFormat:format width:width height:height: mimpapped: NO];
    id<MTLTexture> mtlTexture = [device newTextureWithDescriptor:desc iosurface:iosurface plane:0];

you can then draw on the mtlTexture (for example, using it as a rendertarget) and submit the texture to OpenVR by handing in the underlying `iosurface` object

**Comment by TheDeveloperGuy** [comment]
@natbro Thanks, albeit a bit cryptic and not at all in the context of "how to implement this in a HMD driver", which is what I'm trying to do here, not implement a macOS VR app...

**Comment by natbro** [comment]
not sure what's cryptic about "For any other OpenVR APIs using SharedTextureHandle_t, on macOS this should also be an IOSurfaceRef that you have drawn to in whatever way you choose..." - IVRVirtualDisplay uses a SharedTextureHandle_t, so it is an IOSurfaceRef.

**Comment by TheDeveloperGuy** [comment]
@natbro Thanks, that's probably enough to get me started.
