### ISSUE TITLE
macOS: How to lock texture passed to IVRVirtualDisplay::Present &  IVRDriverDirectModeComponent::Submit?

### ISSUE THREAD

**Issue by TheDeveloperGuy** [ValveSoftware/openvr#748]
On Windows the following code is used:

		// Get mutex from texture
		IDXGIKeyedMutex *pSyncMutex = NULL;
		pTexture->QueryInterface(__uuidof(IDXGIKeyedMutex), (void **)&pSyncMutex));

		// Lock mutex
		pSyncMutex->AcquireSync(0, 10));

How does one synchronise texture access on macOS? The only information I have on this is "Since macOS support is in beta, the texture allocation and submission process is still subject to change, as is how the texture is synchronized - we may need to have the application indicate which MTLCommandQueue they are working on to write to their MTLTexture in order to ensure read/write ordering."

**Comment by natbro** [comment]
`IVRDriverDirectModeComponent` is not implemented on macOS.

for `IVRVirtualDisplay::Present` we haven't yet had anybody implement this interface. there are several different ways we could implement texture synchronization on macOS with Metal depending on how it needs to be used. it would be useful to see where the edge cases are in a native macOS/Metal `IVRVirtualDisplay` implementation and where sync points might express themselves - Metal has some different concepts of sync boundaries around command queues and processes and textures which may cause an in-process driver being handed a shared texture in the form of an IOSurface to not need to explicitly synchronize, as the command queue may correctly order access.

**Comment by TheDeveloperGuy** [comment]
@natbro Thanks, I guess it's a "suck it and see" scenario. Seems a bit at odds with "I've ensured it's working on macOS" 

#551

**Comment by natbro** [comment]
My reply was intending to state that there are multiple options for synchronization and trying to be in the spirit of "let's figure out what will work based on what you're trying, tell me more." IVRVirtualDisplay was designed and tested in collaboration with several Windows-specific drivers. It took several iterations to get it right with them. Ensuring it works on SteamOS and macOS starts out by making sure all the types are platform-neutral and then by tracing that it's being called at the same cadence points. Making it really work outside a synthetic test that the calls are happening happens when somebody wants to really build a driver. If that's what you'd like to do, let's keep chatting. I understand the pace may not be as fast as you like, it's just a matter of prioritizing the most number of customer requests given limited resources.

**Comment by TheDeveloperGuy** [comment]
@natbro Definitely need to get this going at some point, but as macOS SteamVR applications are not exactly numerous, nor are there that many (real, not Hackintosh) Macs that can even run VR, it's not urgent. Right now I'm busy on another project, but hope to have a chance to spend more time on this soon. If I understand you correctly, I'm the only developer trying to get this working right now? Is this the best place to keep chatting?
