### ISSUE TITLE
Expose Access to Raw Accelerometer Data

### ISSUE THREAD

**Issue by danielcchurch** [ValveSoftware/openvr#75]
In [FlyInside](https://flyinside-fsx.com/) I allow a user to recenter their head position (seated) by tapping on their headset.  I do this by reading the accelerometer's linear acceleration value, ovrTrackingState.HeadPose.LinearAcceleration

Could OpenVR expose this same data so that I can easily detect when a user taps on their headset?  I don't want FlyInside for Vive to be an inferior experience to the Rift version.

**Comment by LibreVR** [comment]
I am also dealing with this issue, to provide valid values for `ovrTrackingState.HeadPose.LinearAcceleration`. If OpenVR won't provide these values, I will attempt to derive them from the velocity instead.

If you just differentiate the velocity values you can derive the acceleration value. Assuming that OpenVR will use it's internal acceleration value to predict changes in velocity you could simply recover the acceleration value by doing this:

1. Call `GetDeviceToAbsoluteTrackingPose` with `fPredictedSecondsToPhotonsFromNow` set to 0.0.
2. Call `GetDeviceToAbsoluteTrackingPose` with `fPredictedSecondsToPhotonsFromNow` set to 1.0.
3. Subtract the velocity in 1. from the velocity in 2. which should give you the acceleration value, since the delta time is 1.0 we don't need to divide anything.

I'm not sure how well this works in practice, but in theory it should be fine. However, if the result is 0.0 that probably means OpenVR isn't doing any prediction on the velocity values.

**Comment by jbaicoianu** [comment]
+1, I would also like to work with the raw acceleration data.  This would be useful for adding gesture support to the hand controllers (like shake interactions) and detecting body movements like jumping.

Yes we can derive this in our apps, but it would be much more accurate and convenient if we could just get the data right off the accelerometers.

**Comment by churcd** [comment]
LibreVR, it was a clever idea but unfortunately doesn't work.  The vVelocity component doesn't appear to include any integrated acceleration based upon predicted time, so both velocities are identical.

**Comment by LibreVR** [comment]
@churcd That's unfortunate, in any case you can still derive the value by getting the velocity at set intervals.

**Comment by churcd** [comment]
@LibreVR While it's a good solution for most use-cases, that will miss small instantaneous accelerations, such as those you'd detect from a headset tap.

**Comment by Bobo1239** [comment]
Is this resolved with [v1.0.15](https://github.com/ValveSoftware/openvr/releases/tag/v1.0.15) which added the ability to access raw inertial measurement unit (IMU) data?

**Comment by Avdbergnmf** [comment]
Any update on this? I need to read out the IMU acceleration values for my project. 
Unfortunately, derriving them from the position is too noisy.

**Comment by JoeLudwig** [comment]
For Lighthouse devices, we don't provide this data because it's so heavily device-dependent. (And to be of any use, it would need to be provided alongside calibration values, which are also device-dependent.) For other drivers, we don't have access to this data.

If you need this kind of low-level hardware access, you will probably need to add your own IMU that you can control communication with.

**Comment by Avdbergnmf** [comment]
Alright! Thanks for clarifying 

>
