### ISSUE TITLE
IVRSystem::GetTrackedDeviceIndexForControllerRole doesn't work?

### ISSUE THREAD

**Issue by zezba9000** [ValveSoftware/openvr#780]
When I call "GetTrackedDeviceIndexForControllerRole" for "TrackedControllerRole_LeftHand" it will always return "max uint" aka "(vr::TrackedDeviceIndex_t)(-1)".

"TrackedControllerRole_RightHand" is working correctly but didn't the first couple of times.

Am I hitting a bug or missing some other step?
I init the system like so: "vr::VR_Init(&error, vr::EVRApplicationType::VRApplication_Background);"

For now I'm forced to do the hack of force setting LeftHand to 3 and RightHand to 2.

Using OpenVR v1.0.14

**Comment by AgentMilkshake1** [comment]
Hi Zezba9000,
Bump on this - currently having the exact same issue. I wonder if something has been changed in a Steam VR update that has caused this function to begin returning incorrect information.

**Comment by Karutoh** [comment]
How are you obtraining the role, just fyi not talking about what method/function you used.

**Comment by JoeLudwig** [comment]
What hardware are you using?

On Apr 21, 2018 3:00 AM, Arron Nelson <notifications@github.com> wrote:

How are you obtraining the role, just fyi not talking about what method/function you used.

**Comment by JoeLudwig** [comment]
You can iterate over all tracked device indices up to the max. (There's a constant for that.. vr::k_unMaxTrackedDeviceCount I think) get the tracked device class for each one and look for devices that say they're controllers.

The roles aren't assigned u til after the devices have a pose because we use the head and controller poses to guess which one is in which hand.

On Apr 23, 2018 11:19 AM, Andrew <notifications@github.com> wrote:

Ok looks like roles are invalid unless its tracking? How to I get a device index just to get its batter level regardless or not if its tracking?

Maybe "GetTrackedDeviceIndexForControllerRole" just isn't the correct method to invoke?
How to I get a list of all devices or all controllers, etc connected regardless of role?

So looks like this isn't a bug. Sorry about that.

**Comment by zezba9000** [comment]
Ok got it working as needed tnx.

Now the only other major issue we have with OpenVR used as a Utility is not being able to tell it to exit gracefully: https://github.com/ValveSoftware/openvr/issues/779
