### ISSUE TITLE
Give the 64-bit version a different library name.

### ISSUE THREAD

**Issue by LibreVR** [ValveSoftware/openvr#92]
Please rename the 64-bit version to `openvr_api64.dll` so that it can co-exist with the 32-bit version. This is more consistent with the naming scheme for the Steam API DLLs (`steam_api64.dll`).

**Comment by LibreVR** [comment]
@aleiby Could you also consider this issue for the next release?

**Comment by JoeLudwig** [comment]
The naming convention for SteamVR is to use <platformdir>/<shortname>.<extension> for all binaries. This does mean that you can't mix binaries from multiple platforms in a single directory, but it has numerous other advantages. We have no plans to change the convention.

(Yes, this diverges from what Steam does.)

**Comment by LibreVR** [comment]
Good to know, thanks for the quick reply.

**Comment by GregSlazinski** [comment]
I just found this after posting my issue:
https://github.com/ValveSoftware/openvr/issues/136

I do think you should change it, because being unable to have multiple 32/64 EXE in one folder it's a serious problem.

You can just change it to the following system:
<platformdir>/<shortname><32/64>.<extension>

It's really important,

Thanks
