### ISSUE TITLE
IVRDriverInput_003 in current openvr_driver.h does not allow drivers to publish most reference skeletons

### ISSUE THREAD

**Issue by spayne** [ValveSoftware/openvr#963]
Problem:
If you look at openvr.h you will see clients have the ability to request 4 types of reference poses:
enum EVRSkeletalReferencePose
	{
		VRSkeletalReferencePose_BindPose = 0,
		VRSkeletalReferencePose_OpenHand,
		VRSkeletalReferencePose_Fist,
		VRSkeletalReferencePose_GripLimit
	};
...
	/** Fills the given buffer with the transforms for a specific static skeletal reference pose */
		virtual EVRInputError GetSkeletalReferenceTransforms( VRActionHandle_t action, EVRSkeletalTransformSpace eTransformSpace, EVRSkeletalReferencePose eReferencePose, VR_ARRAY_COUNT( unTransformArrayCount ) VRBoneTransform_t *pTransformArray, uint32_t unTransformArrayCount ) = 0;

On the driver side there are no apis to set those poses. *except* for GripLimit. from openvr_driver.h:
ie notice that there is only griplimit at create time.
IVRDriverInput_003
	/** Creates a skeleton component. */
		virtual EVRInputError CreateSkeletonComponent( PropertyContainerHandle_t ulContainer, const char *pchName, const char *pchSkeletonPath, const char *pchBasePosePath, EVRSkeletalTrackingLevel eSkeletalTrackingLevel, const VRBoneTransform_t *pGripLimitTransforms, uint32_t unGripLimitTransformCount, VRInputComponentHandle_t *pHandle ) = 0

Expected:
1. I expected that either CreateSkeletonComponent took a list of 4 reference skeletons or another call to set the 4 reference transforms.
2. I expected that the reference transforms were documented in the wiki at https://github.com/ValveSoftware/openvr/wiki/Hand-Skeleton.  e.g. pGripLimitTransforms  should be defined or described.

**Comment by joevdh** [comment]
This is by design; all those poses, except for the grip limit, are meant to be controller independent.  They references to be used for user's own range of motion calculations, and internally for finger curl calculation.  


The hand skeleton docs page is meant to do just that: document the hand skeleton, not necessarily all the possible poses you could make with the skeleton.  The grip limit is defined in the documentation for the app code ([https://github.com/ValveSoftware/openvr/wiki/SteamVR-Skeletal-Input](https://github.com/ValveSoftware/openvr/wiki/SteamVR-Skeletal-Input)), I'll update the driver docs with more info.

**Comment by joevdh** [comment]
Yup, that's right.  Sorry for not being more clear in the first response.

**Comment by spayne** [comment]
You weren't unclear.  I appreciate more clarification - thank you.

I've been asked if an openvr driver can support different hand models e.g. consider someone with very long fingers.  I believe the answer is no - there - so rechecking the APIs I thought that perhaps if the driver was able to set the reference poses then maybe that would mean the driver would be able to use different hand models.

**Comment by joevdh** [comment]
Yeah, the goal of the system is to enable apps to run without modification using any input device.  So the skeleton that the apps get from the drivers is rigidly defined so that its consistent.  

However, once the skeletal data get to the app, the app can do anything it wants with it, including retargetting the skeletal data to a different skeleton, and using any arbitrary hand model.
